import type { DemoIntakeFixtures } from "../demo-intake-types.js";

export const DEMO_INTAKE_FIXTURES: DemoIntakeFixtures = {
  company: {
    name: "Acme Bank",
    description: "A fictional retail and commercial bank."
  },
  hero: {
    key: "hero-credit-limit",
    name: "Credit-limit-increase assistant",
    description: "AI agent to assist customers with credit limit increases",
    businessContext: "Customer service tool to handle routine requests",
    dataSensitivity: "confidential",
    complianceTags: ["gdpr", "ccpa"],
    targetStatus: "proposed",
    intendedAgentNames: ["claude-opus", "gemini-pro"],
    intake: {
      title: "Credit-limit-increase assistant",
      description: "AI agent to assist customers with credit limit increases",
      euAiAct: {
        purposeDomain: "essential-services",
        affectedPersons: ["customers"],
        decisionAutonomy: "human-reviews",
        biometricUse: "none",
        emotionRecognition: false,
        socialScoring: false,
        manipulativeTechniques: false,
        profilesNaturalPersons: true,
        safetyComponent: false,
        interactsWithHumans: true,
        generatesSyntheticContent: true
      },
      context: {
        sectors: ["financial-services"],
        dataCategories: ["personal", "financial"],
        deployment: "customer-facing",
        euNexus: true,
        usesExternalVendor: true,
        generative: true,
        autonomousActions: true,
        toolsUsed: ["crm.read"]
      },
      draftNarrative: false
    }
  },
  vendors: [
    {
      key: "vendor-anthropic",
      name: "Anthropic",
      description: "Provider of Claude models",
      category: "model_provider",
      linkedAgentProviders: ["anthropic"],
      targetStatus: "approved"
    },
    {
      key: "vendor-openai",
      name: "OpenAI",
      description: "Provider of GPT models",
      category: "model_provider",
      linkedAgentProviders: ["openai"],
      targetStatus: "approved"
    },
    {
      key: "vendor-google",
      name: "Google Cloud",
      description: "Provider of Gemini models",
      category: "model_provider",
      linkedAgentProviders: ["google"],
      targetStatus: "under_assessment"
    },
    {
      key: "vendor-xai",
      name: "xAI",
      description: "Provider of Grok models",
      category: "model_provider",
      linkedAgentProviders: ["xai"],
      targetStatus: "proposed"
    },
    {
      key: "vendor-mock",
      name: "Acme Internal Mock",
      description: "Internal mock services",
      category: "model_provider",
      linkedAgentProviders: ["mock"],
      targetStatus: "rejected"
    }
  ],
  useCases: [
    {
      key: "uc-1",
      name: "HR Resume Screener",
      description: "Screens resumes for job applicants",
      businessContext: "HR productivity",
      dataSensitivity: "confidential",
      complianceTags: ["gdpr"],
      targetStatus: "under_review",
      intendedAgentNames: ["gpt-5"],
      intake: {
        title: "HR Resume Screener",
        description: "Screens resumes for job applicants",
        euAiAct: {
          purposeDomain: "employment-hr",
          affectedPersons: ["general-public"],
          decisionAutonomy: "informs-human",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["general"],
          dataCategories: ["personal"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-2",
      name: "Customer Sentiment Analyzer",
      description: "Analyzes support tickets",
      businessContext: "Customer service",
      dataSensitivity: "confidential",
      complianceTags: [],
      targetStatus: "approved",
      intendedAgentNames: ["claude-opus"],
      intake: {
        title: "Customer Sentiment Analyzer",
        description: "Analyzes support tickets",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: ["customers"],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: true,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["financial-services"],
          dataCategories: ["personal"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-3",
      name: "Social Credit Scorer",
      description: "Prohibited use case",
      businessContext: "Risk management",
      dataSensitivity: "regulated",
      complianceTags: [],
      targetStatus: "rejected",
      decisionReason: "Prohibited under EU AI Act",
      intendedAgentNames: ["gemini-pro"],
      intake: {
        title: "Social Credit Scorer",
        description: "Prohibited use case",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: ["customers"],
          decisionAutonomy: "fully-automated",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: true,
          manipulativeTechniques: false,
          profilesNaturalPersons: true,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["financial-services"],
          dataCategories: ["personal", "financial"],
          deployment: "customer-facing",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: true,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-4",
      name: "Internal Knowledge Base Bot",
      description: "Answers internal queries",
      businessContext: "IT Support",
      dataSensitivity: "internal",
      complianceTags: [],
      targetStatus: "approved",
      intendedAgentNames: ["balanced-mock"],
      intake: {
        title: "Internal Knowledge Base Bot",
        description: "Answers internal queries",
        euAiAct: {
          purposeDomain: "internal-productivity",
          affectedPersons: ["employees"],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: true,
          generatesSyntheticContent: true
        },
        context: {
          sectors: ["general"],
          dataCategories: ["proprietary"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: false,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-5",
      name: "Marketing Copy Generator",
      description: "Generates blog posts",
      businessContext: "Marketing",
      dataSensitivity: "public",
      complianceTags: [],
      targetStatus: "retired",
      decisionReason: "Replaced by newer system",
      intendedAgentNames: ["fast-mock"],
      intake: {
        title: "Marketing Copy Generator",
        description: "Generates blog posts",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: [],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: true
        },
        context: {
          sectors: ["general"],
          dataCategories: ["proprietary"],
          deployment: "internal",
          euNexus: false,
          usesExternalVendor: false,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-6",
      name: "Fraud Detection Engine",
      description: "Detects fraudulent transactions",
      businessContext: "Risk",
      dataSensitivity: "regulated",
      complianceTags: ["pci"],
      targetStatus: "approved",
      intendedAgentNames: ["premium-mock"],
      intake: {
        title: "Fraud Detection Engine",
        description: "Detects fraudulent transactions",
        euAiAct: {
          purposeDomain: "essential-services",
          affectedPersons: ["customers"],
          decisionAutonomy: "narrow-procedural",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["financial-services"],
          dataCategories: ["financial"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: false,
          generative: false,
          autonomousActions: true,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-7",
      name: "Code Copilot",
      description: "Assists developers",
      businessContext: "Engineering",
      dataSensitivity: "internal",
      complianceTags: [],
      targetStatus: "proposed",
      intendedAgentNames: ["gpt-5"],
      intake: {
        title: "Code Copilot",
        description: "Assists developers",
        euAiAct: {
          purposeDomain: "internal-productivity",
          affectedPersons: ["employees"],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: true,
          generatesSyntheticContent: true
        },
        context: {
          sectors: ["general"],
          dataCategories: ["proprietary"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-8",
      name: "Legal Contract Analyzer",
      description: "Analyzes contracts",
      businessContext: "Legal",
      dataSensitivity: "confidential",
      complianceTags: [],
      targetStatus: "under_review",
      intendedAgentNames: ["claude-opus"],
      intake: {
        title: "Legal Contract Analyzer",
        description: "Analyzes contracts",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: ["employees"],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["general"],
          dataCategories: ["proprietary"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-9",
      name: "Call Center Voice Assistant",
      description: "Automated phone tree",
      businessContext: "Customer support",
      dataSensitivity: "confidential",
      complianceTags: [],
      targetStatus: "proposed",
      intendedAgentNames: ["gemini-pro"],
      intake: {
        title: "Call Center Voice Assistant",
        description: "Automated phone tree",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: ["customers"],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: true,
          generatesSyntheticContent: true
        },
        context: {
          sectors: ["general"],
          dataCategories: ["personal"],
          deployment: "customer-facing",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    },
    {
      key: "uc-10",
      name: "Financial Forecasting",
      description: "Predicts revenue",
      businessContext: "Finance",
      dataSensitivity: "confidential",
      complianceTags: [],
      targetStatus: "approved",
      intendedAgentNames: ["grok"],
      intake: {
        title: "Financial Forecasting",
        description: "Predicts revenue",
        euAiAct: {
          purposeDomain: "general-business",
          affectedPersons: [],
          decisionAutonomy: "human-reviews",
          biometricUse: "none",
          emotionRecognition: false,
          socialScoring: false,
          manipulativeTechniques: false,
          profilesNaturalPersons: false,
          safetyComponent: false,
          interactsWithHumans: false,
          generatesSyntheticContent: false
        },
        context: {
          sectors: ["financial-services"],
          dataCategories: ["financial"],
          deployment: "internal",
          euNexus: true,
          usesExternalVendor: true,
          generative: true,
          autonomousActions: false,
          toolsUsed: []
        },
        draftNarrative: false
      }
    }
  ],
  risks: [
    {
      key: "risk-1",
      useCaseKey: "uc-2",
      title: "Risk 1",
      description: "Description of risk 1",
      category: "bias_fairness",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-2",
      useCaseKey: "uc-3",
      title: "Risk 2",
      description: "Description of risk 2",
      category: "unsafe_output",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-3",
      useCaseKey: "uc-4",
      title: "Risk 3",
      description: "Description of risk 3",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-4",
      useCaseKey: "uc-5",
      title: "Risk 4",
      description: "Description of risk 4",
      category: "data_leakage_pii",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-5",
      useCaseKey: "uc-6",
      title: "Risk 5",
      description: "Description of risk 5",
      category: "over_permissioning",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-6",
      useCaseKey: "uc-7",
      title: "Risk 6",
      description: "Description of risk 6",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-7",
      useCaseKey: "uc-8",
      title: "Risk 7",
      description: "Description of risk 7",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-8",
      useCaseKey: "uc-9",
      title: "Risk 8",
      description: "Description of risk 8",
      category: "third_party_ai",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-9",
      useCaseKey: "uc-10",
      title: "Risk 9",
      description: "Description of risk 9",
      category: "budget_overrun",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-10",
      useCaseKey: "uc-1",
      title: "Risk 10",
      description: "Description of risk 10",
      category: "scope_drift",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-11",
      useCaseKey: "uc-2",
      title: "Risk 11",
      description: "Description of risk 11",
      category: "hallucination",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-12",
      useCaseKey: "uc-3",
      title: "Risk 12",
      description: "Description of risk 12",
      category: "bias_fairness",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-13",
      useCaseKey: "uc-4",
      title: "Risk 13",
      description: "Description of risk 13",
      category: "unsafe_output",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-14",
      useCaseKey: "uc-5",
      title: "Risk 14",
      description: "Description of risk 14",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-15",
      useCaseKey: "uc-6",
      title: "Risk 15",
      description: "Description of risk 15",
      category: "data_leakage_pii",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-16",
      useCaseKey: "uc-7",
      title: "Risk 16",
      description: "Description of risk 16",
      category: "over_permissioning",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-17",
      useCaseKey: "uc-8",
      title: "Risk 17",
      description: "Description of risk 17",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-18",
      useCaseKey: "uc-9",
      title: "Risk 18",
      description: "Description of risk 18",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "mitigating",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      mitigation: "Mitigation implemented",
      residual: { likelihood: "low", impact: "medium" },
    },
    {
      key: "risk-19",
      useCaseKey: "uc-10",
      title: "Risk 19",
      description: "Description of risk 19",
      category: "third_party_ai",
      likelihood: "medium",
      impact: "high",
      targetStatus: "accepted",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      acceptanceNote: "Accepted business risk",
    },
    {
      key: "risk-20",
      useCaseKey: "uc-1",
      title: "Risk 20",
      description: "Description of risk 20",
      category: "budget_overrun",
      likelihood: "medium",
      impact: "high",
      targetStatus: "accepted",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      acceptanceNote: "Accepted business risk",
    },
    {
      key: "risk-21",
      useCaseKey: "uc-2",
      title: "Risk 21",
      description: "Description of risk 21",
      category: "scope_drift",
      likelihood: "medium",
      impact: "high",
      targetStatus: "closed",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      closeReason: "No longer relevant",
    },
    {
      key: "risk-22",
      useCaseKey: "uc-3",
      title: "Risk 22",
      description: "Description of risk 22",
      category: "hallucination",
      likelihood: "medium",
      impact: "high",
      targetStatus: "closed",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      closeReason: "No longer relevant",
    },
    {
      key: "risk-23",
      useCaseKey: "uc-4",
      title: "Risk 23",
      description: "Description of risk 23",
      category: "bias_fairness",
      likelihood: "medium",
      impact: "high",
      targetStatus: "closed",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      closeReason: "No longer relevant",
    },
    {
      key: "risk-24",
      useCaseKey: "uc-5",
      title: "Risk 24",
      description: "Description of risk 24",
      category: "unsafe_output",
      likelihood: "medium",
      impact: "high",
      targetStatus: "closed",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
      closeReason: "No longer relevant",
    },
    {
      key: "risk-25",
      useCaseKey: "uc-6",
      title: "Risk 25",
      description: "Description of risk 25",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
    {
      key: "risk-26",
      useCaseKey: "uc-7",
      title: "Risk 26",
      description: "Description of risk 26",
      category: "data_leakage_pii",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
    {
      key: "risk-27",
      useCaseKey: "uc-8",
      title: "Risk 27",
      description: "Description of risk 27",
      category: "over_permissioning",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
    {
      key: "risk-28",
      useCaseKey: "uc-9",
      title: "Risk 28",
      description: "Description of risk 28",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
    {
      key: "risk-29",
      useCaseKey: "uc-10",
      title: "Risk 29",
      description: "Description of risk 29",
      category: "prompt_injection",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
    {
      key: "risk-30",
      useCaseKey: "uc-1",
      title: "Risk 30",
      description: "Description of risk 30",
      category: "third_party_ai",
      likelihood: "medium",
      impact: "high",
      targetStatus: "open",
      controls: ["eu-ai-act:art-15-accuracy-robustness"],
    },
  ],
  modelCards: [
    {
      agentName: "claude-opus",
      intendedUse: "General purpose reasoning",
      dataClaims: { "training_data": "public internet" },
      limitations: "May hallucinate facts",
      biasFairness: [{ status: "assessed", method: "documented disparity evaluation", dimension: "demographic parity", resultRef: "https://example.com/report1", assessedAt: "2026-01-01T00:00:00Z" }],
      standardRefs: []
    },
    {
      agentName: "gpt-5",
      intendedUse: "Text generation",
      dataClaims: {},
      limitations: "None stated",
      biasFairness: [{ status: "assessed", method: "documented disparity evaluation", dimension: "equalized odds", resultRef: "https://example.com/report2", assessedAt: "2026-01-01T00:00:00Z" }],
      standardRefs: []
    },
    {
      agentName: "gemini-pro",
      intendedUse: "Multimodal tasks",
      dataClaims: {},
      limitations: "None stated",
      biasFairness: [{ status: "in_progress", method: "documented disparity evaluation", dimension: "demographic parity" }],
      standardRefs: []
    },
    {
      agentName: "grok",
      intendedUse: "Real-time query",
      dataClaims: {},
      limitations: "None",
      biasFairness: [],
      standardRefs: []
    },
    {
      agentName: "fast-mock",
      intendedUse: "Mock",
      dataClaims: {},
      limitations: "Mock",
      biasFairness: [],
      standardRefs: []
    },
    {
      agentName: "balanced-mock",
      intendedUse: "Mock",
      dataClaims: {},
      limitations: "Mock",
      biasFairness: [],
      standardRefs: []
    },
    {
      agentName: "premium-mock",
      intendedUse: "Mock",
      dataClaims: {},
      limitations: "Mock",
      biasFairness: [],
      standardRefs: []
    }
  ],
  shadowAi: [
    { appName: "Grammarly", vendorHost: "grammarly.com", grantedBy: "user-1@acme.example", installCount: 50 },
    { appName: "Notion AI", vendorHost: "notion.so", grantedBy: "user-2@acme.example", installCount: 20 },
    { appName: "Github Copilot", vendorHost: "github.com", grantedBy: "user-3@acme.example", installCount: 150 },
    { appName: "Jasper", vendorHost: "jasper.ai", grantedBy: "user-4@acme.example", installCount: 5 },
    { appName: "Otter", vendorHost: "otter.ai", grantedBy: "user-5@acme.example", installCount: 30 },
    { appName: "Midjourney", vendorHost: "midjourney.com", grantedBy: "user-6@acme.example", installCount: 10 }
  ]
};
