/**
 * ADR-0053 — THE STABILITY REGISTRY.
 *
 * One line per registered route, carrying the ONLY thing a reviewer has to
 * decide when they add a route: is this part of the published contract, and if
 * so how strong is the promise?
 *
 *   public-stable  in the published spec and the generated client. A breaking
 *                  change needs a NEW MAJOR PATH (/v2) plus the full 12-month
 *                  deprecation window. Tagging a route this way is a
 *                  commitment, not a default.
 *   public-beta    in the published spec and client, clearly labelled. May
 *                  change inside the major with the shorter beta window.
 *   internal       NOT in the published artifact and carrying NO compatibility
 *                  guarantee. This is the default for a reason: admin/console
 *                  surfaces must stay free to move.
 *
 * WHAT KEEPS THIS FILE HONEST. It is not documentation — it is an assertion,
 * checked by openapi.test.ts against the live Fastify route inventory. A route
 * added without a line here fails the suite; a line here naming a route that no
 * longer exists fails the suite. There is no way to ship a spec that has
 * drifted from the routes without the suite going red first.
 *
 * WHAT THIS FILE DOES NOT DECIDE. The auth class. That is derived, per route,
 * from route-classes.ts — the very sets the gateway's two gates branch on — so
 * the document can never claim a route is public when the gate says admin.
 *
 * GENERATED ONCE from the live inventory (ADR-0053's "audit of existing /v1
 * routes to assign stability tags" prerequisite), HAND-CURATED thereafter.
 */

export type Stability = "public-stable" | "public-beta" | "internal";

export const ROUTE_STABILITY: Readonly<Record<string, Stability>> = {
  "GET /": "internal",
  "GET /admin": "internal",
  "GET /app": "internal",
  "POST /auth/change-password": "internal",
  "POST /auth/login": "internal",
  "POST /auth/login-with-key": "internal",
  "POST /auth/logout": "internal",
  "GET /auth/me": "internal",
  "POST /auth/mfa/verify": "internal",
  "GET /auth/oidc/:providerId/start": "internal",
  "GET /auth/oidc/callback": "internal",
  "GET /auth/oidc/providers": "internal",
  "GET /auth/oidc/:providerId/login": "internal",
  "GET /auth/sign-in-options": "internal",
  "GET /auth/link/pending": "internal",
  "POST /auth/link/confirm": "internal",
  "POST /auth/saml/:providerId/acs": "internal",
  "GET /auth/saml/:providerId/metadata": "internal",
  "GET /auth/saml/:providerId/start": "internal",
  "GET /auth/saml/providers": "internal",
  "GET /auth/sessions": "internal",
  "POST /auth/sessions/:sessionId/revoke": "internal",
  "POST /auth/sessions/revoke-others": "internal",
  "POST /auth/totp/activate": "internal",
  "POST /auth/totp/disable": "internal",
  "POST /auth/totp/enroll": "internal",
  "POST /auth/username": "internal",
  "GET /health": "public-stable",
  // ADR-0097 — RFC 9728 protected-resource metadata. `public-stable` because
  // the RFC pins the path and the shape; the CONTENTS are derived from what
  // this gateway actually accepts, which is what makes it safe to publish.
  "GET /.well-known/oauth-protected-resource": "public-stable",
  "GET /.well-known/oauth-protected-resource/mcp/:serverId": "public-stable",
  "POST /mcp/:serverId": "public-beta",
  "GET /scim/v2/Groups": "internal",
  "POST /scim/v2/Groups": "internal",
  "DELETE /scim/v2/Groups/:id": "internal",
  "GET /scim/v2/Groups/:id": "internal",
  "PATCH /scim/v2/Groups/:id": "internal",
  "PUT /scim/v2/Groups/:id": "internal",
  "GET /scim/v2/ServiceProviderConfig": "internal",
  "GET /scim/v2/Users": "internal",
  "POST /scim/v2/Users": "internal",
  "DELETE /scim/v2/Users/:id": "internal",
  "GET /scim/v2/Users/:id": "internal",
  "PATCH /scim/v2/Users/:id": "internal",
  "PUT /scim/v2/Users/:id": "internal",
  "GET /ui": "internal",
  "GET /ui/*": "internal",
  "GET /v1/abac/policies": "internal",
  "POST /v1/abac/policies": "internal",
  "DELETE /v1/abac/policies/:policyId": "internal",
  "GET /v1/abac/policies/:policyId": "internal",
  "POST /v1/abac/policies/:policyId/activate": "internal",
  "POST /v1/abac/policies/:policyId/deactivate": "internal",
  "POST /v1/abac/policies/:policyId/test": "internal",
  "POST /v1/abac/policies/:policyId/versions": "internal",
  "GET /v1/abac/schema": "internal",
  "POST /v1/abac/simulate": "internal",
  "POST /v1/abac/test": "internal",
  "POST /v1/abac/validate": "internal",
  "GET /v1/agents": "public-stable",
  // ADR-0066 §4 — the fallback chain is deployment CONFIGURATION whose shape
  // may still change; internal until it has lived in a real deployment.
  "GET /v1/agents/:agentId/fallbacks": "internal",
  "PUT /v1/agents/:agentId/fallbacks": "internal",
  "POST /v1/agents": "internal",
  // B1.5 — the versioned agent_config edit surface (model + list prices).
  "PATCH /v1/agents/:agentId": "internal",
  "POST /v1/agents/:agentId/enabled": "internal",
  "POST /v1/agents/:agentId/invoke": "public-stable",
  // ADR-0089 — ownership + lifecycle, admin governance writes on the registry.
  "POST /v1/agents/:agentId/lifecycle": "internal",
  "POST /v1/agents/:agentId/owner": "internal",
  // ADR-0168 amendment item 6 — stewardship (admin or current steward).
  "PATCH /v1/agents/:agentId/stewardship": "internal",
  "POST /v1/agents/:agentId/stewardship/review": "internal",
  "POST /v1/agents/:agentId/system-prompt": "internal",
  // ADR-0175 review fix — the binding expected served model (admin console)
  "PUT /v1/agents/:agentId/expected-served-model": "internal",
  "GET /v1/api/versioning": "public-stable",
  "GET /v1/approvals": "public-stable",
  "POST /v1/approvals/:approvalId/claim": "internal",
  "POST /v1/approvals/:approvalId/decide": "public-stable",
  "GET /v1/approvals/assignment-rules": "internal",
  "POST /v1/approvals/assignment-rules": "internal",
  "DELETE /v1/approvals/assignment-rules/:id": "internal",
  "POST /v1/approvals/bulk": "internal",
  "GET /v1/approvals/sla-policies": "internal",
  "POST /v1/approvals/sla-policies": "internal",
  "DELETE /v1/approvals/sla-policies/:id": "internal",
  "POST /v1/approvals/sla/sweep": "internal",
  "GET /v1/approvals/views": "internal",
  "POST /v1/approvals/views": "internal",
  "DELETE /v1/approvals/views/:id": "internal",
  "GET /v1/approvals/workload": "internal",
  "GET /v1/audit": "public-stable",
  "GET /v1/audit.csv": "public-stable",
  // ADR-0116 — the export-signing key's fingerprint, the OUT-OF-BAND
  // publication point an admin reads once and hands to an auditor. `internal`
  // on purpose: it is an operator surface, not something an SDK calls, and a
  // verifier must never fetch it (that would put the running product back in
  // the verification path, which is the thing the bundle exists to escape).
  "GET /v1/exports/signing-key": "internal",
  "POST /v1/audit/prune": "internal",
  "GET /v1/audit/retention": "internal",
  // ADR-0060 — the tamper-evident chain's operator surface. `internal` on
  // purpose: the response shape is a disclosure document (limits, anchor
  // provenance, the legacy boundary) and is expected to grow as the anchor
  // sinks do, so it is not frozen into the public-stable contract yet.
  "GET /v1/audit/verify": "internal",
  "POST /v1/audit/anchor": "internal",
  "POST /v1/audit/anchors/flush": "internal",
  "GET /v1/audit/anchors": "internal",
  "GET /v1/auth/oidc-providers": "internal",
  "POST /v1/auth/oidc-providers": "internal",
  "DELETE /v1/auth/oidc-providers/:providerId": "internal",
  "PATCH /v1/auth/oidc-providers/:providerId": "internal",
  "GET /v1/auth/link-requests": "internal",
  "POST /v1/auth/link-requests/:requestId/approve": "internal",
  "POST /v1/auth/link-requests/:requestId/deny": "internal",
  "GET /v1/auth/saml-providers": "internal",
  "POST /v1/auth/saml-providers": "internal",
  "DELETE /v1/auth/saml-providers/:providerId": "internal",
  "PATCH /v1/auth/saml-providers/:providerId": "internal",
  "GET /v1/billing/overview": "internal",
  "GET /v1/billing/periods": "internal",
  "POST /v1/billing/periods": "internal",
  "POST /v1/billing/periods/:id/close": "internal",
  "POST /v1/billing/periods/:id/statements": "internal",
  "GET /v1/billing/rate-cards": "internal",
  "POST /v1/billing/rate-cards": "internal",
  "GET /v1/billing/rate-cards/:id": "internal",
  "GET /v1/billing/statements": "public-beta",
  "GET /v1/billing/statements/:id": "public-beta",
  "GET /v1/billing/statements/:id/export": "internal",
  "POST /v1/billing/statements/:id/issue": "internal",
  "POST /v1/billing/statements/:id/reconcile": "internal",
  "POST /v1/chat/completions": "public-beta",
  "GET /v1/compliance/profiles": "internal",
  "POST /v1/compliance/profiles": "internal",
  "GET /v1/config-versions/:artifactType/:artifactId": "internal",
  "POST /v1/config-versions/:artifactType/:artifactId": "internal",
  "POST /v1/config-versions/:artifactType/:artifactId/activate": "internal",
  "DELETE /v1/config-versions/:artifactType/:artifactId/canary": "internal",
  "POST /v1/config-versions/:artifactType/:artifactId/canary": "internal",
  "POST /v1/config-versions/:artifactType/:artifactId/promote": "internal",
  "POST /v1/config-versions/:artifactType/:artifactId/rollback": "internal",
  "GET /v1/config-versions/:artifactType/:artifactId/traffic": "internal",
  // ADR-0073 — the shadow-canary divergence surfaces
  "GET /v1/config-versions/canaries": "internal",
  "GET /v1/config-versions/:artifactType/:artifactId/divergence": "internal",
  "POST /v1/config-versions/observations/prune": "internal",
  "GET /v1/connectors": "public-stable",
  "POST /v1/connectors": "internal",
  "DELETE /v1/connectors/:connectorId/credential": "internal",
  "GET /v1/connectors/:connectorId/credential": "internal",
  "POST /v1/connectors/:connectorId/credential": "internal",
  "POST /v1/connectors/:connectorId/invoke": "public-stable",
  "GET /v1/conversations": "public-beta",
  "POST /v1/conversations": "public-beta",
  "DELETE /v1/conversations/:conversationId": "public-beta",
  "GET /v1/conversations/:conversationId": "public-beta",
  "GET /v1/cost-events": "public-stable",
  // ADR-0069 — cross-vendor cost consolidation. Internal while the adapter
  // vocabulary is still settling: adding a vendor adapter changes the accepted
  // `adapter` values, and a public-stable contract would freeze that list.
  "GET /v1/cost-consolidated": "internal",
  // ADR-0070 — trace observability. INTERNAL on purpose: a trace's span shape
  // is exactly the kind of thing that should stay free to move while the
  // feature settles, and pinning it into the published contract now would
  // freeze a data model one week old.
  "GET /v1/traces": "internal",
  "GET /v1/traces/:traceId": "internal",
  "GET /v1/sessions": "internal",
  "GET /v1/tracing/config": "internal",
  "POST /v1/tracing/export": "internal",
  "GET /v1/cost-imports": "internal",
  "POST /v1/cost-imports": "internal",
  "GET /v1/cost-imports/adapters": "internal",
  "GET /v1/cost-imports/mappings": "internal",
  "POST /v1/cost-imports/mappings": "internal",
  "DELETE /v1/cost-imports/mappings/:aliasId": "internal",
  "POST /v1/cost-imports/domain-rules": "internal",
  "DELETE /v1/cost-imports/domain-rules/:ruleId": "internal",
  // ADR-0076: reconciliation (run-now + health/report) and the roster ingest
  "POST /v1/cost-imports/reconcile": "internal",
  "GET /v1/cost-imports/reconciliation": "internal",
  "POST /v1/cost-imports/roster": "internal",
  "DELETE /v1/cost-imports/:importId": "internal",
  "GET /v1/cost-imports/:importId": "internal",
  "GET /v1/costs/unattributed": "internal",
  "GET /v1/custom-model-providers": "internal",
  "POST /v1/custom-model-providers": "internal",
  "DELETE /v1/custom-model-providers/:providerId": "internal",
  "PATCH /v1/custom-model-providers/:providerId": "internal",
  "POST /v1/custom-model-providers/:providerId/enabled": "internal",
  "POST /v1/custom-model-providers/:providerId/test": "internal",
  "GET /v1/decisions": "internal",
  "POST /v1/decisions": "internal",
  "GET /v1/delegations": "internal",
  "POST /v1/delegations": "internal",
  "DELETE /v1/delegations/:delegationId": "internal",
  "GET /v1/deploy/targets": "internal",
  "POST /v1/deploy/targets": "internal",
  "DELETE /v1/deploy/targets/:name": "internal",
  "GET /v1/egress-allow-hosts": "internal",
  "POST /v1/egress-allow-hosts": "internal",
  "DELETE /v1/egress-allow-hosts/:hostId": "internal",
  "GET /v1/evals/datasets": "internal",
  "POST /v1/evals/datasets": "internal",
  "GET /v1/evals/datasets/:id": "internal",
  "POST /v1/evals/datasets/:id/cases": "internal",
  "DELETE /v1/evals/datasets/:id/cases/:caseId": "internal",
  "POST /v1/evals/datasets/:id/versions": "internal",
  "GET /v1/evals/runs": "internal",
  "POST /v1/evals/runs": "public-beta",
  "GET /v1/evals/runs/:id": "internal",
  "POST /v1/evals/runs/:id/baseline": "internal",
  "GET /v1/evals/scorers": "internal",
  "GET /v1/evals/scoring-semantics": "internal",
  "GET /v1/evals/summary": "internal",
  // ADR-0088 — registered external eval scorers
  "GET /v1/external-scorers": "internal",
  "POST /v1/external-scorers": "internal",
  "PATCH /v1/external-scorers/:scorerId": "internal",
  "DELETE /v1/external-scorers/:scorerId": "internal",
  "POST /v1/external-scorers/:scorerId/test": "internal",
  "POST /v1/external-scorers/:scorerId/enabled": "internal",
  "POST /v1/authz/check": "public-stable",
  "POST /v1/evaluate": "public-stable",
  "GET /v1/git/connections": "internal",
  "POST /v1/git/connections": "internal",
  "POST /v1/grants/agents": "internal",
  "DELETE /v1/grants/agents/:grantId": "internal",
  "POST /v1/grants/connectors": "internal",
  "DELETE /v1/grants/connectors/:grantId": "internal",
  "POST /v1/grants/servers": "internal",
  "POST /v1/grants/tools": "internal",
  "GET /v1/group-role-mappings": "internal",
  "POST /v1/group-role-mappings": "internal",
  "DELETE /v1/group-role-mappings/:mappingId": "internal",
  "GET /v1/group-role-mappings/asserted-groups": "internal",
  "GET /v1/guardrails/config": "internal",
  "PUT /v1/guardrails/config": "internal",
  "DELETE /v1/guardrails/config/:scope/:scopeId": "internal",
  "PUT /v1/guardrails/config/:scope/:scopeId": "internal",
  "GET /v1/guardrails/detectors": "internal",
  "GET /v1/guardrails/effective": "internal",
  "POST /v1/guardrails/sample": "internal",
  "GET /v1/guardrails/violations": "internal",
  "GET /v1/health/schedulers": "internal",
  "GET /v1/infra/backups": "internal",
  "POST /v1/infra/backups/:backupId/restore": "internal",
  "GET /v1/infra/certs": "internal",
  "POST /v1/infra/certs/:certId/rotate": "internal",
  "GET /v1/infra/certs/:certId/rotations": "internal",
  "GET /v1/infra/findings": "internal",
  "POST /v1/infra/findings/:findingId/remediate": "internal",
  "GET /v1/infra/patches": "internal",
  "POST /v1/infra/patches/:patchId/apply": "internal",
  "GET /v1/infra/policies": "internal",
  "POST /v1/infra/policies": "internal",
  "GET /v1/infra/posture": "internal",
  "GET /v1/infra/resources": "internal",
  "POST /v1/infra/resources": "internal",
  "POST /v1/infra/scan": "internal",
  "GET /v1/initiatives": "internal",
  "POST /v1/initiatives": "internal",
  "DELETE /v1/initiatives/:initiativeId": "internal",
  "GET /v1/initiatives/:initiativeId": "internal",
  "PATCH /v1/initiatives/:initiativeId": "internal",
  "GET /v1/interception/effective": "internal",
  "GET /v1/interception/scope-rules": "internal",
  "POST /v1/interception/scope-rules": "internal",
  "DELETE /v1/interception/scope-rules/:ruleId": "internal",
  "PATCH /v1/interception/scope-rules/:ruleId": "internal",
  "GET /v1/interception/settings": "internal",
  "PUT /v1/interception/settings": "internal",
  "GET /v1/keys": "public-stable",
  "POST /v1/keys/:keyId/revoke": "public-stable",
  "GET /v1/licenses": "internal",
  "POST /v1/licenses": "internal",
  "GET /v1/licenses/:id": "internal",
  "GET /v1/licenses/status": "internal",
  "GET /v1/licenses/verifications": "internal",
  "POST /v1/licenses/verify": "internal",
  // ADR-0065 — RegulAIt-LLM. INTERNAL, every one of them: this is a console
  // surface for building and governing a custom model, and an admin/console
  // surface must stay free to move. Nothing here is part of the published
  // contract, and the honest way to say that is a stability tag rather than an
  // undocumented route.
  "GET /v1/llm/backends": "internal",
  "PUT /v1/llm/backend-configs/:backend": "internal",
  "DELETE /v1/llm/backend-configs/:backend": "internal",
  "GET /v1/llm/datasets": "internal",
  "POST /v1/llm/datasets": "internal",
  "GET /v1/llm/datasets/:id": "internal",
  "POST /v1/llm/datasets/:id/rows": "internal",
  "POST /v1/llm/datasets/:id/versions": "internal",
  "POST /v1/llm/datasets/:id/validate": "internal",
  "GET /v1/llm/jobs": "internal",
  "POST /v1/llm/jobs": "internal",
  "GET /v1/llm/jobs/:id": "internal",
  "POST /v1/llm/jobs/:id/cancel": "internal",
  "POST /v1/llm/jobs/:id/poll": "internal",
  "POST /v1/llm/jobs/poll-sweep": "internal",
  "GET /v1/llm/artifacts": "internal",
  "GET /v1/llm/artifacts/:id": "internal",
  "POST /v1/llm/artifacts/:id/query": "internal",
  "POST /v1/llm/artifacts/:id/register": "internal",
  "GET /v1/lineage": "public-beta",
  "GET /v1/lineage/nodes": "public-beta",
  "GET /v1/lineage/overview": "internal",
  "GET /v1/lineage/runs/:runId": "public-beta",
  "GET /v1/me": "public-stable",
  "POST /v1/messages": "public-beta",
  "GET /v1/model-credentials": "internal",
  "POST /v1/model-credentials": "internal",
  "DELETE /v1/model-credentials/:provider": "internal",
  "GET /v1/model-providers/status": "internal",
  // ADR-0066 §1 — the OpenAI/Anthropic discovery endpoint. public-beta beside
  // the two shims it serves: same surface, same admin toggle, same maturity.
  "GET /v1/models": "public-beta",
  "GET /v1/mrm/cards": "internal",
  "POST /v1/mrm/cards": "internal",
  "DELETE /v1/mrm/cards/:id": "internal",
  "GET /v1/mrm/cards/:id": "internal",
  "PATCH /v1/mrm/cards/:id": "internal",
  "POST /v1/mrm/cards/:id/evidence": "internal",
  "DELETE /v1/mrm/cards/:id/evidence/:evidenceId": "internal",
  "POST /v1/mrm/cards/:id/revoke": "internal",
  "POST /v1/mrm/cards/:id/sign-off": "internal",
  "POST /v1/mrm/enforcement": "internal",
  "GET /v1/mrm/expiring": "internal",
  "POST /v1/mrm/expiry-sweep": "internal",
  "GET /v1/mrm/status": "internal",
  "GET /v1/onboarding": "internal",
  "POST /v1/onboarding/compliance-pack": "internal",
  "GET /v1/onboarding/export": "internal",
  "GET /v1/onboarding/imports": "internal",
  "POST /v1/onboarding/imports/group-roles": "internal",
  "POST /v1/onboarding/imports/users": "internal",
  "POST /v1/onboarding/roles/seed": "internal",
  "POST /v1/onboarding/steps/:stepKey": "internal",
  "GET /v1/openapi.json": "public-stable",
  "GET /v1/org/posture": "internal",
  "POST /v1/org/posture/harden": "internal",
  "GET /v1/org/settings": "internal",
  "PUT /v1/org/settings": "internal",
  "GET /v1/pm/connections": "internal",
  "POST /v1/pm/connections": "internal",
  "GET /v1/pm/links": "internal",
  "POST /v1/pm/webhooks/:connectionName": "internal",
  "GET /v1/projects": "public-stable",
  "POST /v1/projects": "public-stable",
  "PATCH /v1/projects/:projectId": "internal",
  "POST /v1/projects/:projectId/classifications": "internal",
  "GET /v1/projects/:projectId/compliance": "internal",
  "GET /v1/projects/:projectId/context": "internal",
  "POST /v1/projects/:projectId/context": "internal",
  "GET /v1/projects/:projectId/context/graph": "internal",
  "POST /v1/projects/:projectId/context/promote": "internal",
  "GET /v1/projects/:projectId/costs": "public-stable",
  "GET /v1/projects/:projectId/costs.csv": "public-stable",
  "GET /v1/projects/:projectId/members": "internal",
  "POST /v1/projects/:projectId/members": "internal",
  "DELETE /v1/projects/:projectId/members/:userId": "internal",
  "PATCH /v1/projects/:projectId/members/:userId": "internal",
  // ADR-0082 — the standing agent dependency inventory. Internal: an admin
  // governance read whose aggregation shape is expected to grow.
  "GET /v1/inventory/agents": "internal",
  "GET /v1/inventory/agents/:agentId": "internal",
  "GET /v1/agents/:agentId/card": "internal",
  "GET /v1/inventory/graph": "internal",
  // ADR-0173 batch 2b — the run graph (a console view, not a published contract)
  "GET /v1/run-graph/builder-turn/:threadId/:turn": "internal",
  "GET /v1/run-graph/orchestration/:runId": "internal",
  "GET /v1/run-graph/use-case/:useCaseId": "internal",
  "GET /v1/governance/alerts": "internal",
  // ADR-0175 A7 / A15 — the credential inventory and the energy estimate (admin console)
  "GET /v1/admin/credentials": "internal",
  "GET /v1/energy/factors": "internal",
  "PUT /v1/energy/factors": "internal",
  "DELETE /v1/energy/factors/:factorId": "internal",
  "GET /v1/energy/estimate": "internal",
  "GET /v1/regulatory/updates": "internal",
  "GET /v1/governance/alerts/:alertId/remediation": "internal",
  "POST /v1/governance/alerts/:alertId/remediation": "internal",
  "GET /v1/governance/remediations": "internal",
  "GET /v1/governance/trace-evaluations": "internal",
  "POST /v1/governance/trace-evaluations/run": "internal",
  "POST /v1/gates/deploy": "internal",
  "PATCH /v1/chatops/connections/:connectionId": "internal",
  "POST /v1/governance/alerts/:alertId/post": "internal",
  "POST /v1/governance/monitor/evaluate": "internal",
  "POST /v1/governance/alerts/:alertId/acknowledge": "internal",
  // ADR-0090 — grant certification campaigns. Internal: admin governance
  // surfaces over the org's own grant rows (the decisions themselves ride
  // the existing POST /v1/approvals/:approvalId/decide).
  "POST /v1/certification-campaigns": "internal",
  "POST /v1/certification-campaigns/preview": "internal",
  "GET /v1/certification-campaigns": "internal",
  "GET /v1/certification-campaigns/:campaignId": "internal",
  // ADR-0090 amendment (B2) — the expiry sweep's manual door (records
  // visibility facts only; decides nothing) and audited item reassignment
  // (never to the grant's holder).
  "POST /v1/certification-campaigns/expiry-sweep": "internal",
  "POST /v1/certification-campaigns/:campaignId/items/:itemId/reassign": "internal",
  // ADR-0090 — the two direct MCP grant deletes that never existed (every
  // other grant kind already had a removal endpoint); internal like their
  // agent/connector twins' write surfaces.
  "DELETE /v1/grants/tools/:grantId": "internal",
  "DELETE /v1/grants/servers/:grantId": "internal",
  // ADR-0092 — access recommendations, the deterministic half: read-only
  // queries-with-reasons over the ledgers. Internal: an admin governance
  // read whose rule set is versioned and expected to grow by version.
  "GET /v1/recommendations/access": "internal",
  // ADR-0091 — toxic-combination SoD: rule CRUD + override escalations.
  // Internal: admin governance over the org's own grant policy (override
  // DECISIONS ride the existing POST /v1/approvals/:approvalId/decide).
  "POST /v1/sod/rules": "internal",
  "GET /v1/sod/rules": "internal",
  "PATCH /v1/sod/rules/:ruleId": "internal",
  "DELETE /v1/sod/rules/:ruleId": "internal",
  "POST /v1/sod/overrides": "internal",
  "GET /v1/sod/overrides": "internal",
  "GET /v1/reports/definitions": "internal",
  "POST /v1/reports/definitions": "internal",
  "DELETE /v1/reports/definitions/:id": "internal",
  "GET /v1/reports/definitions/:id": "internal",
  "POST /v1/reports/definitions/:id/generate": "internal",
  "POST /v1/reports/definitions/:id/schedules": "internal",
  "GET /v1/reports/overview": "internal",
  // ADR-0082 — the boardroom posture one-pager; internal like the overview.
  "GET /v1/reports/posture": "internal",
  "GET /v1/reports/trust": "internal",
  "GET /v1/reports/runs": "public-beta",
  "GET /v1/reports/runs/:id": "public-beta",
  "GET /v1/reports/runs/:id/export": "internal",
  "GET /v1/reports/schedules": "internal",
  "DELETE /v1/reports/schedules/:id": "internal",
  "PATCH /v1/reports/schedules/:id": "internal",
  "POST /v1/reports/schedules/run-due": "internal",
  "GET /v1/redteam/attack-classes": "internal",
  "GET /v1/redteam/findings": "internal",
  "GET /v1/redteam/libraries": "internal",
  "POST /v1/redteam/libraries": "internal",
  "POST /v1/redteam/libraries/seed": "internal",
  "GET /v1/redteam/libraries/:id": "internal",
  "POST /v1/redteam/libraries/:id/probes": "internal",
  "POST /v1/redteam/libraries/:id/publish": "internal",
  "POST /v1/redteam/libraries/:id/versions": "internal",
  "GET /v1/redteam/runs": "internal",
  "POST /v1/redteam/runs": "internal",
  "GET /v1/redteam/runs/:id": "internal",
  // ADR-0068: the per-trial record behind an ASR
  "GET /v1/redteam/runs/:id/trials": "internal",
  "POST /v1/redteam/runs/:id/evidence": "internal",
  "GET /v1/redteam/summary": "internal",
  // ADR-0081 — the AI risk register: new surface, internal until the shape settles
  "GET /v1/risks": "internal",
  "POST /v1/risks": "internal",
  "GET /v1/risks/library": "internal",
  "GET /v1/risks/scenarios": "internal",
  "GET /v1/risks/:riskId": "internal",
  "PATCH /v1/risks/:riskId": "internal",
  "POST /v1/risks/:riskId/transition": "internal",
  "POST /v1/risks/:riskId/accept": "internal",
  "PUT /v1/risks/:riskId/residual": "internal",
  "POST /v1/risks/:riskId/controls": "internal",
  "DELETE /v1/risks/:riskId/controls/:controlRef": "internal",
  "POST /v1/policy-simulations": "internal",
  "GET /v1/policy-simulations": "internal",
  "GET /v1/policy-simulations/:id": "internal",
  "GET /v1/policy-simulations/settings": "internal",
  "PUT /v1/policy-simulations/settings": "internal",
  "GET /v1/revocations": "internal",
  "POST /v1/revocations": "internal",
  "PATCH /v1/revocations/:kind/:revocationId/scope": "internal",
  "DELETE /v1/revocations/:revocationId": "internal",
  "GET /v1/roles": "public-stable",
  "POST /v1/roles": "public-stable",
  "DELETE /v1/roles/:roleId": "public-stable",
  "GET /v1/roles/:roleId/assignments": "public-stable",
  "GET /v1/roles/:roleId/grants": "public-stable",
  "POST /v1/roles/:roleId/grants/agents": "internal",
  "DELETE /v1/roles/:roleId/grants/agents/:grantId": "internal",
  "POST /v1/roles/:roleId/grants/connectors": "internal",
  "DELETE /v1/roles/:roleId/grants/connectors/:grantId": "internal",
  "POST /v1/roles/:roleId/grants/servers": "internal",
  "DELETE /v1/roles/:roleId/grants/servers/:grantId": "internal",
  "POST /v1/roles/:roleId/grants/tools": "internal",
  "DELETE /v1/roles/:roleId/grants/tools/:grantId": "internal",
  "PATCH /v1/rules/:kind/:ruleId/deploy-mode": "internal",
  "PATCH /v1/rules/:kind/:ruleId": "internal",
  "DELETE /v1/rules/:kind/:ruleId": "internal",
  "GET /v1/rules/approvals": "internal",
  "POST /v1/rules/approvals": "internal",
  "GET /v1/rules/data-scopes": "internal",
  "POST /v1/rules/data-scopes": "internal",
  "GET /v1/rules/rate-limits": "internal",
  "POST /v1/rules/rate-limits": "internal",
  "GET /v1/runs": "public-beta",
  "POST /v1/runs": "public-beta",
  "GET /v1/runs/:runId": "public-beta",
  "POST /v1/runs/:runId/auto": "internal",
  "POST /v1/runs/:runId/events": "internal",
  "POST /v1/runs/:runId/nodes/:nodeId/dispatch": "internal",
  "POST /v1/runs/:runId/pm-sync": "internal",
  "POST /v1/runs/decompose": "public-beta",
  "GET /v1/scim/status": "internal",
  "GET /v1/scim/tokens": "internal",
  "POST /v1/scim/tokens": "internal",
  "POST /v1/scim/tokens/:tokenId/revoke": "internal",
  "POST /v1/scim/tokens/:tokenId/rotate": "internal",
  "GET /v1/servers": "public-stable",
  "POST /v1/servers": "internal",
  "PATCH /v1/servers/:serverId": "internal",
  "GET /v1/servers/:serverId/tools": "internal",
  "POST /v1/servers/:serverId/tools": "internal",
  // ADR-0097 — the MCP admission review surface
  "GET /v1/mcp/admission": "internal",
  // ADR-0101 — federated MCP registries. Internal: an operator console surface
  // (configure an upstream, pull its catalogue, import one entry), not part of
  // the published integration contract.
  "POST /v1/mcp-registries": "internal",
  "GET /v1/mcp-registries": "internal",
  "PATCH /v1/mcp-registries/:registryId": "internal",
  "POST /v1/mcp-registries/:registryId/sync": "internal",
  "GET /v1/mcp-registries/:registryId/entries": "internal",
  "POST /v1/mcp-registries/entries/:entryId/import": "internal",
  "POST /v1/servers/:serverId/admission/clear": "internal",
  // ADR-0175 A6/A5 — the builder-skill review queue and the release-age
  // cooldown's admin surface (operator console, admin-only)
  "GET /v1/admission/skills": "internal",
  "POST /v1/admission/skills/:id/admit": "internal",
  "POST /v1/admission/skills/:id/visibility": "internal",
  "GET /v1/release-quarantine": "internal",
  "POST /v1/release-quarantine/override": "internal",
  "PATCH /v1/servers/:serverId/tools/:toolName/price": "internal",
  "GET /v1/setup/status": "internal",
  // ADR-0063 — REGULAIT_DATA_KEY custody. Internal: an operator/admin console
  // surface about this deployment's own envelope key, not an integration
  // contract anyone builds against.
  "GET /v1/security/data-key": "internal",
  "GET /v1/security/data-key/attestations": "internal",
  "POST /v1/security/data-key/attestations": "internal",
  "GET /v1/security/data-key/reencryption": "internal",
  // ADR-0064 — the in-process scheduler. Internal: an operator console surface
  // about THIS deployment's own background loop. Nothing integrates against it,
  // and "run now" on a job that spends model tokens is not a contract we want
  // anyone building a client around.
  "GET /v1/scheduler": "internal",
  "GET /v1/scheduler/jobs/:name/runs": "internal",
  "PATCH /v1/scheduler/jobs/:name": "internal",
  "POST /v1/scheduler/jobs/:name/run": "internal",
  // ADR-0044 §5 / ADR-0057 — the two sweeps that got an endpoint alongside
  // their scheduler job, so the manual path exists and is the same function.
  "POST /v1/evals/drift-sweep": "internal",
  "POST /v1/redteam/scheduled-sweep": "internal",
  // ADR-0061 — ChatOps approvals. Internal: an admin console surface plus a
  // provider-shaped callback whose contract is Slack's, not ours.
  "GET /v1/chatops/connections": "internal",
  "POST /v1/chatops/connections": "internal",
  "DELETE /v1/chatops/connections/:connectionId": "internal",
  "GET /v1/chatops/identity-links": "internal",
  "POST /v1/chatops/identity-links": "internal",
  "DELETE /v1/chatops/identity-links/:linkId": "internal",
  "POST /v1/chatops/approvals/:approvalId/post": "internal",
  "POST /v1/chatops/:connectionName/interactions": "internal",
  // ADR-0173 §2 — inbound conversations to builder agents. Internal for the
  // same reason: provider-shaped callbacks whose contract is Slack's / Teams'.
  "POST /v1/chatops/:connectionName/events": "internal",
  "POST /v1/chatops/:connectionName/messages": "internal",
  // ADR-0173 batch 2b — the Teams Bot Framework endpoint (the platform's contract)
  "POST /v1/chatops/:connectionName/bot": "internal",
  "GET /v1/chatops/builder-routes": "internal",
  "PUT /v1/chatops/builder-routes/:channelId": "internal",
  // ADR-0056 — the governance copilot. Internal: the tool vocabulary, the
  // query plan and the evidence envelope will move as more ledgers become
  // readable, and an answer shape is not a contract we want to freeze while no
  // model provider is even connected.
  "GET /v1/copilot/tools": "internal",
  "POST /v1/copilot/ask": "internal",
  "GET /v1/copilot/queries": "internal",
  "POST /v1/copilot/proposals": "internal",
  "GET /v1/copilot/proposals": "internal",
  // L6b — the consent-gated applier. Internal for the same reason the rest of
  // the copilot is: it names governance objects and is an admin surface.
  "POST /v1/copilot/proposals/:proposalId/apply": "internal",
  // ADR-0172 — the agent builder. Internal: phase 1 of a console surface whose
  // shapes (toolbox execution, channels, bundles) move in phase 2.
  "GET /v1/builder/agents": "internal",
  "POST /v1/builder/agents": "internal",
  "POST /v1/builder/agents/import": "internal",
  "GET /v1/builder/agents/:id": "internal",
  "PATCH /v1/builder/agents/:id": "internal",
  "DELETE /v1/builder/agents/:id": "internal",
  "PUT /v1/builder/agents/:id/tools": "internal",
  "PUT /v1/builder/agents/:id/subagents": "internal",
  "PUT /v1/builder/agents/:id/skills": "internal",
  "POST /v1/builder/agents/:id/skills/:skillId/reattach": "internal",
  "POST /v1/builder/agents/:id/memory": "internal",
  "DELETE /v1/builder/agents/:id/memory/:memoryId": "internal",
  "POST /v1/builder/agents/:id/schedules": "internal",
  "PATCH /v1/builder/agents/:id/schedules/:scheduleId": "internal",
  "DELETE /v1/builder/agents/:id/schedules/:scheduleId": "internal",
  "POST /v1/builder/agents/:id/channels": "internal",
  "DELETE /v1/builder/agents/:id/channels/:channelId": "internal",
  "GET /v1/builder/agents/:id/export": "internal",
  "POST /v1/builder/agents/:id/chat": "internal",
  "POST /v1/builder/schedules/sweep": "internal",
  "GET /v1/builder/threads": "internal",
  "GET /v1/builder/threads/:id": "internal",
  "PATCH /v1/builder/threads/:id": "internal",
  "POST /v1/builder/threads/:id/steps/:stepId/confirm": "internal",
  "POST /v1/builder/threads/:id/steps/:stepId/cancel": "internal",
  "GET /v1/builder/skills": "internal",
  "POST /v1/builder/skills": "internal",
  "POST /v1/builder/skills/import": "internal",
  "GET /v1/builder/skills/:id": "internal",
  "PATCH /v1/builder/skills/:id": "internal",
  "DELETE /v1/builder/skills/:id": "internal",
  "GET /v1/builder/templates": "internal",
  "GET /v1/builder/templates/:id": "internal",
  "GET /v1/builder/integrations": "internal",
  "GET /v1/builder/toolbox-options": "internal",
  "GET /v1/builder/usage": "internal",
  // ADR-0058 — compliance packs. Internal: the pack schema and the collector
  // vocabulary will move as frameworks are revised and new ledgers become
  // evidenceable, and freezing a control-mapping shape as a public contract
  // would make a framework revision a breaking API change.
  "GET /v1/compliance/packs": "internal",
  "POST /v1/compliance/packs": "internal",
  "POST /v1/compliance/packs/seed": "internal",
  "GET /v1/compliance/packs/:id": "internal",
  "POST /v1/compliance/packs/:id/activate": "internal",
  "DELETE /v1/compliance/packs/:id": "internal",
  "POST /v1/compliance/packs/:id/attestations": "internal",
  "POST /v1/compliance/packs/:id/evaluate": "internal",
  "GET /v1/compliance/pack-reports": "internal",
  "GET /v1/compliance/pack-reports/:id": "internal",
  // ADR-0087 — the pack-version diff + impact preview, same reasoning
  "GET /v1/compliance-packs/:framework/diff": "internal",
  // ADR-0055 — shadow-AI discovery. Internal: the evidence-import shape and the
  // finding schema will move as the catalogue and the collectors evolve, and an
  // admin console surface is not a contract we want to freeze.
  "GET /v1/shadow-ai/catalogue": "internal",
  "POST /v1/shadow-ai/catalogue": "internal",
  "POST /v1/shadow-ai/catalogue/seed": "internal",
  "DELETE /v1/shadow-ai/catalogue/:signatureId": "internal",
  "GET /v1/shadow-ai/findings": "internal",
  "POST /v1/shadow-ai/findings/:findingId/disposition": "internal",
  "POST /v1/shadow-ai/findings/:findingId/remediate": "internal",
  "GET /v1/shadow-ai/findings/:findingId/remediation-plan": "internal",
  "GET /v1/shadow-ai/imports": "internal",
  "POST /v1/shadow-ai/imports": "internal",
  "GET /v1/shadow-ai/adapters": "internal",
  "POST /v1/shadow-ai/imports/raw": "internal",
  "GET /v1/shadow-ai/discovery/catalog": "internal",
  "POST /v1/shadow-ai/discovery": "internal",
  "POST /v1/shadow-ai/mcp-discovery": "internal",
  "GET /v1/spend/anomalies": "public-beta",
  "PATCH /v1/spend/anomalies/:id": "internal",
  "POST /v1/spend/anomalies/evaluate": "internal",
  "GET /v1/spend/forecast": "public-beta",
  "GET /v1/spend/monitor-overview": "internal",
  "GET /v1/spend/monitor-policies": "internal",
  "PUT /v1/spend/monitor-policies": "internal",
  "GET /v1/spend/scheduled-changes": "internal",
  "POST /v1/spend/scheduled-changes": "internal",
  "DELETE /v1/spend/scheduled-changes/:id": "internal",
  "GET /v1/teams": "internal",
  "POST /v1/teams": "internal",
  "DELETE /v1/teams/:teamId": "internal",
  "POST /v1/teams/:teamId/members": "internal",
  "DELETE /v1/teams/:teamId/members/:userId": "internal",
  "GET /v1/usage-events": "public-stable",
  // ADR-0080 — the AI use-case registry: new surface, internal until the shape settles
  "GET /v1/use-cases": "internal",
  "POST /v1/use-cases": "internal",
  "POST /v1/use-cases/intake/assist": "internal",
  "GET /v1/use-cases/:useCaseId/overview": "internal",
  "GET /v1/use-cases/:useCaseId": "internal",
  // ADR-0123 — the framework mapping. Internal like its siblings until the
  // use-cases surface as a whole is published.
  "GET /v1/use-cases/:useCaseId/frameworks": "internal",
  // ADR-0171 — the intake wizard's drafts: a UI convenience, never published
  "GET /v1/use-cases/draft": "internal",
  "PUT /v1/use-cases/draft": "internal",
  "DELETE /v1/use-cases/draft": "internal",
  // ADR-0124
  "GET /v1/execution": "internal",
  // ADR-0173 §3 — the model allow-list matrix
  "GET /v1/model-policy": "internal",
  "PUT /v1/model-policy": "internal",
  // ADR-0173 batch 2b — the prompt registry, the playground and outbound webhooks
  "GET /v1/prompts": "internal",
  "POST /v1/prompts": "internal",
  "GET /v1/prompts/resolve": "internal",
  "GET /v1/prompts/:promptId": "internal",
  "PATCH /v1/prompts/:promptId": "internal",
  "DELETE /v1/prompts/:promptId": "internal",
  "POST /v1/prompts/:promptId/commits": "internal",
  "GET /v1/prompts/:promptId/commits/:hash": "internal",
  "GET /v1/prompts/:promptId/diff": "internal",
  "PUT /v1/prompts/:promptId/tags/:tag": "internal",
  "POST /v1/playground/run": "internal",
  "POST /v1/playground/evaluate": "internal",
  "GET /v1/webhooks/events": "internal",
  "GET /v1/webhooks": "internal",
  "POST /v1/webhooks": "internal",
  "PATCH /v1/webhooks/:subscriptionId": "internal",
  "DELETE /v1/webhooks/:subscriptionId": "internal",
  "POST /v1/webhooks/:subscriptionId/rotate-secret": "internal",
  "POST /v1/webhooks/:subscriptionId/test": "internal",
  "GET /v1/webhooks/:subscriptionId/deliveries": "internal",
  "POST /v1/webhooks/deliveries/:deliveryId/retry": "internal",
  "POST /v1/webhooks/sweep": "internal",
  // ADR-0173 batch 2c (E) — the evaluator catalog, datasets from traces, compare, judge calibration
  "GET /v1/evals/catalog": "internal",
  "GET /v1/evals/catalog/tested-by": "internal",
  "POST /v1/evals/datasets/:id/from-traces": "internal",
  "POST /v1/evals/traces/evaluate": "internal",
  "GET /v1/evals/compare": "internal",
  "POST /v1/evals/runs/:id/calibration": "internal",
  "PUT /v1/execution/mode": "internal",
  "POST /v1/agents/:agentId/halt": "internal",
  "POST /v1/agents/:agentId/unhalt": "internal",
  "POST /v1/servers/:serverId/tools/:toolName/halt": "internal",
  "POST /v1/servers/:serverId/tools/:toolName/unhalt": "internal",
  "PATCH /v1/use-cases/:useCaseId": "internal",
  "POST /v1/use-cases/:useCaseId/retire": "internal",
  // ADR-0168 — mark an approval condition met (owner/use-case owner/admin)
  "POST /v1/use-cases/:useCaseId/conditions/:conditionId/met": "internal",
  // ADR-0168 amendment — review policy and recertification sweep
  "GET /v1/governance/review-policy": "internal",
  "PUT /v1/governance/review-policy": "internal",
  "POST /v1/governance/recertification/sweep": "internal",
  // ADR-0084 — the AI vendor registry: new surface, internal until the shape settles
  "GET /v1/vendors": "internal",
  "POST /v1/vendors": "internal",
  "GET /v1/vendors/:vendorId": "internal",
  "PATCH /v1/vendors/:vendorId": "internal",
  "POST /v1/vendors/:vendorId/attestations": "internal",
  "POST /v1/vendors/:vendorId/retire": "internal",
  "GET /v1/users": "public-stable",
  "POST /v1/users": "public-stable",
  "PATCH /v1/users/:userId": "public-stable",
  "POST /v1/users/:userId/admin": "internal",
  "POST /v1/users/:userId/agent-policy": "internal",
  "GET /v1/users/:userId/agents": "public-stable",
  "GET /v1/users/:userId/connectors": "public-stable",
  // ADR-0069 — a person's OWN consolidated (metered + imported) spend. In
  // NON_ADMIN_ROUTES; the handler refuses unless the caller IS this user.
  "GET /v1/users/:userId/cost-consolidated": "internal",
  "PUT /v1/users/:userId/cost-center": "internal",
  "POST /v1/users/:userId/deactivate": "public-stable",
  "POST /v1/users/:userId/keys": "public-stable",
  "POST /v1/users/:userId/mfa/clear": "internal",
  "GET /v1/users/:userId/model-credentials": "internal",
  "POST /v1/users/:userId/model-credentials": "internal",
  "DELETE /v1/users/:userId/model-credentials/:provider": "internal",
  "POST /v1/users/:userId/reactivate": "public-stable",
  "GET /v1/users/:userId/revocations/agents": "internal",
  "POST /v1/users/:userId/revocations/agents": "internal",
  "DELETE /v1/users/:userId/revocations/agents/:revocationId": "internal",
  "GET /v1/users/:userId/revocations/connectors": "internal",
  "POST /v1/users/:userId/revocations/connectors": "internal",
  "DELETE /v1/users/:userId/revocations/connectors/:revocationId": "internal",
  "GET /v1/users/:userId/role-provenance": "internal",
  "POST /v1/users/:userId/roles": "public-stable",
  "DELETE /v1/users/:userId/roles/:roleId": "public-stable",
  "GET /v1/users/:userId/servers/:serverId/entitlements": "internal",
  "GET /v1/users/:userId/servers/:serverId/tools": "public-stable",
  "GET /v1/users/:userId/sessions": "internal",
  "POST /v1/users/:userId/sessions/:sessionId/revoke": "internal",
  "POST /v1/users/:userId/sessions/revoke": "internal",
  "POST /v1/users/:userId/set-initial-password": "internal",
  "PUT /v1/users/:userId/username": "internal",
  "GET /v1/users/directory": "public-stable",
  // ADR-0066 §2 — virtual keys. public-beta: the shape is settled and the
  // adoption story depends on an SDK being able to mint and revoke these,
  // but per-key budget semantics may still gain a period window.
  "GET /v1/virtual-keys": "public-beta",
  "POST /v1/virtual-keys": "public-beta",
  "PATCH /v1/virtual-keys/:keyId": "public-beta",
  "DELETE /v1/virtual-keys/:keyId": "public-beta",
  "GET /v1/virtual-keys/:keyId/usage": "public-beta",
  "GET /v1/workflows/assignment-rules": "internal",
  "POST /v1/workflows/assignment-rules": "internal",
  "DELETE /v1/workflows/assignment-rules/:ruleId": "internal",
  "GET /v1/workflows/instances": "public-stable",
  "POST /v1/workflows/instances": "public-stable",
  "GET /v1/workflows/instances/:instanceId": "public-stable",
  "POST /v1/workflows/instances/:instanceId/abort": "internal",
  "POST /v1/workflows/instances/:instanceId/advance": "public-stable",
  "POST /v1/workflows/instances/:instanceId/artifacts": "internal",
  "POST /v1/workflows/instances/:instanceId/checks": "internal",
  "POST /v1/workflows/instances/:instanceId/deploy-override": "internal",
  "POST /v1/workflows/instances/:instanceId/pm-sync": "internal",
  "POST /v1/workflows/instances/:instanceId/recheck": "internal",
  "GET /v1/workflows/template-gallery": "internal",
  "POST /v1/workflows/template-gallery/:galleryId/create": "internal",
  "GET /v1/workflows/templates": "internal",
  "POST /v1/workflows/templates": "internal",
  "POST /v1/workflows/templates/:templateId/retire": "internal",
};

/**
 * ADR-0053 §6 — the provider-compatibility surfaces. These conform to
 * ANTHROPIC'S and OPENAI'S published request/response schemas by design (that
 * is the entire point of ADR-0020/0024 interception: an off-the-shelf vendor
 * SDK must work unchanged). Re-specifying them here would be to claim ownership
 * of a shape we deliberately do not own, and would go stale the moment the
 * vendor moves. They are listed in the document as compatibility surfaces with
 * a pointer upstream, and carry no RegulAIt-authored body schema.
 */
export const COMPAT_SURFACES: Readonly<Record<string, string>> = {
  "POST /v1/messages": "https://docs.anthropic.com/en/api/messages",
  "POST /v1/chat/completions": "https://platform.openai.com/docs/api-reference/chat",
  "POST /mcp/:serverId": "https://modelcontextprotocol.io/specification",
};

/** the tag each route is grouped under in the published document */
export const ROUTE_TAGS: Readonly<Record<string, string>> = {
  "GET /": "web",
  "GET /admin": "web",
  "GET /app": "web",
  "POST /auth/change-password": "auth",
  "POST /auth/login": "auth",
  "POST /auth/login-with-key": "auth",
  "POST /auth/logout": "auth",
  "GET /auth/me": "auth",
  "POST /auth/mfa/verify": "auth",
  "GET /auth/oidc/:providerId/start": "auth",
  "GET /auth/oidc/callback": "auth",
  "GET /auth/oidc/providers": "auth",
  "GET /auth/oidc/:providerId/login": "auth",
  "GET /auth/sign-in-options": "auth",
  "GET /auth/link/pending": "auth",
  "POST /auth/link/confirm": "auth",
  "POST /auth/saml/:providerId/acs": "auth",
  "GET /auth/saml/:providerId/metadata": "auth",
  "GET /auth/saml/:providerId/start": "auth",
  "GET /auth/saml/providers": "auth",
  "GET /auth/sessions": "auth",
  "POST /auth/sessions/:sessionId/revoke": "auth",
  "POST /auth/sessions/revoke-others": "auth",
  "POST /auth/totp/activate": "auth",
  "POST /auth/totp/disable": "auth",
  "POST /auth/totp/enroll": "auth",
  "POST /auth/username": "auth",
  "GET /health": "health",
  "GET /.well-known/oauth-protected-resource": "mcp-proxy",
  "GET /.well-known/oauth-protected-resource/mcp/:serverId": "mcp-proxy",
  "POST /mcp/:serverId": "mcp-proxy",
  "GET /scim/v2/Groups": "misc",
  "POST /scim/v2/Groups": "misc",
  "DELETE /scim/v2/Groups/:id": "misc",
  "GET /scim/v2/Groups/:id": "misc",
  "PATCH /scim/v2/Groups/:id": "misc",
  "PUT /scim/v2/Groups/:id": "misc",
  "GET /scim/v2/ServiceProviderConfig": "misc",
  "GET /scim/v2/Users": "misc",
  "POST /scim/v2/Users": "misc",
  "DELETE /scim/v2/Users/:id": "misc",
  "GET /scim/v2/Users/:id": "misc",
  "PATCH /scim/v2/Users/:id": "misc",
  "PUT /scim/v2/Users/:id": "misc",
  "GET /ui": "web",
  "GET /ui/*": "web",
  "GET /v1/abac/policies": "abac",
  "POST /v1/abac/policies": "abac",
  "DELETE /v1/abac/policies/:policyId": "abac",
  "GET /v1/abac/policies/:policyId": "abac",
  "POST /v1/abac/policies/:policyId/activate": "abac",
  "POST /v1/abac/policies/:policyId/deactivate": "abac",
  "POST /v1/abac/policies/:policyId/test": "abac",
  "POST /v1/abac/policies/:policyId/versions": "abac",
  "GET /v1/abac/schema": "abac",
  "POST /v1/abac/simulate": "abac",
  "POST /v1/abac/test": "abac",
  "POST /v1/abac/validate": "abac",
  "GET /v1/agents": "agents",
  "GET /v1/agents/:agentId/fallbacks": "agents",
  "PUT /v1/agents/:agentId/fallbacks": "agents",
  "POST /v1/agents": "agents",
  "PATCH /v1/agents/:agentId": "agents",
  "POST /v1/agents/:agentId/enabled": "agents",
  "POST /v1/agents/:agentId/invoke": "agents",
  "POST /v1/agents/:agentId/lifecycle": "agents",
  "POST /v1/agents/:agentId/owner": "agents",
  "PATCH /v1/agents/:agentId/stewardship": "agents",
  "POST /v1/agents/:agentId/stewardship/review": "agents",
  "POST /v1/agents/:agentId/system-prompt": "agents",
  "PUT /v1/agents/:agentId/expected-served-model": "agents",
  "GET /v1/api/versioning": "api",
  "GET /v1/approvals": "approvals",
  "POST /v1/approvals/:approvalId/claim": "approvals",
  "POST /v1/approvals/:approvalId/decide": "approvals",
  "GET /v1/approvals/assignment-rules": "approvals",
  "POST /v1/approvals/assignment-rules": "approvals",
  "DELETE /v1/approvals/assignment-rules/:id": "approvals",
  "POST /v1/approvals/bulk": "approvals",
  "GET /v1/approvals/sla-policies": "approvals",
  "POST /v1/approvals/sla-policies": "approvals",
  "DELETE /v1/approvals/sla-policies/:id": "approvals",
  "POST /v1/approvals/sla/sweep": "approvals",
  "GET /v1/approvals/views": "approvals",
  "POST /v1/approvals/views": "approvals",
  "DELETE /v1/approvals/views/:id": "approvals",
  "GET /v1/approvals/workload": "approvals",
  "GET /v1/audit": "audit",
  "GET /v1/audit.csv": "audit",
  "GET /v1/exports/signing-key": "audit",
  "POST /v1/audit/prune": "audit",
  "GET /v1/audit/verify": "audit",
  "POST /v1/audit/anchor": "audit",
  "POST /v1/audit/anchors/flush": "audit",
  "GET /v1/audit/anchors": "audit",
  "GET /v1/audit/retention": "audit",
  "GET /v1/auth/oidc-providers": "auth",
  "POST /v1/auth/oidc-providers": "auth",
  "DELETE /v1/auth/oidc-providers/:providerId": "auth",
  "PATCH /v1/auth/oidc-providers/:providerId": "auth",
  "GET /v1/auth/link-requests": "auth",
  "POST /v1/auth/link-requests/:requestId/approve": "auth",
  "POST /v1/auth/link-requests/:requestId/deny": "auth",
  "GET /v1/auth/saml-providers": "auth",
  "POST /v1/auth/saml-providers": "auth",
  "DELETE /v1/auth/saml-providers/:providerId": "auth",
  "PATCH /v1/auth/saml-providers/:providerId": "auth",
  "GET /v1/billing/overview": "billing",
  "GET /v1/billing/periods": "billing",
  "POST /v1/billing/periods": "billing",
  "POST /v1/billing/periods/:id/close": "billing",
  "POST /v1/billing/periods/:id/statements": "billing",
  "GET /v1/billing/rate-cards": "billing",
  "POST /v1/billing/rate-cards": "billing",
  "GET /v1/billing/rate-cards/:id": "billing",
  "GET /v1/billing/statements": "billing",
  "GET /v1/billing/statements/:id": "billing",
  "GET /v1/billing/statements/:id/export": "billing",
  "POST /v1/billing/statements/:id/issue": "billing",
  "POST /v1/billing/statements/:id/reconcile": "billing",
  "POST /v1/chat/completions": "chat",
  "GET /v1/compliance/profiles": "compliance",
  "POST /v1/compliance/profiles": "compliance",
  "GET /v1/config-versions/:artifactType/:artifactId": "config-versions",
  "POST /v1/config-versions/:artifactType/:artifactId": "config-versions",
  "POST /v1/config-versions/:artifactType/:artifactId/activate": "config-versions",
  "DELETE /v1/config-versions/:artifactType/:artifactId/canary": "config-versions",
  "POST /v1/config-versions/:artifactType/:artifactId/canary": "config-versions",
  "POST /v1/config-versions/:artifactType/:artifactId/promote": "config-versions",
  "POST /v1/config-versions/:artifactType/:artifactId/rollback": "config-versions",
  "GET /v1/config-versions/:artifactType/:artifactId/traffic": "config-versions",
  "GET /v1/config-versions/canaries": "config-versions",
  "GET /v1/config-versions/:artifactType/:artifactId/divergence": "config-versions",
  "POST /v1/config-versions/observations/prune": "config-versions",
  "GET /v1/connectors": "connectors",
  "POST /v1/connectors": "connectors",
  "DELETE /v1/connectors/:connectorId/credential": "connectors",
  "GET /v1/connectors/:connectorId/credential": "connectors",
  "POST /v1/connectors/:connectorId/credential": "connectors",
  "POST /v1/connectors/:connectorId/invoke": "connectors",
  "GET /v1/conversations": "conversations",
  "POST /v1/conversations": "conversations",
  "DELETE /v1/conversations/:conversationId": "conversations",
  "GET /v1/conversations/:conversationId": "conversations",
  "GET /v1/cost-events": "cost-events",
  "GET /v1/cost-consolidated": "cost-imports",
  "GET /v1/traces": "tracing",
  "GET /v1/traces/:traceId": "tracing",
  "GET /v1/sessions": "tracing",
  "GET /v1/tracing/config": "tracing",
  "POST /v1/tracing/export": "tracing",
  "GET /v1/cost-imports": "cost-imports",
  "POST /v1/cost-imports": "cost-imports",
  "GET /v1/cost-imports/adapters": "cost-imports",
  "GET /v1/cost-imports/mappings": "cost-imports",
  "POST /v1/cost-imports/mappings": "cost-imports",
  "DELETE /v1/cost-imports/mappings/:aliasId": "cost-imports",
  "POST /v1/cost-imports/domain-rules": "cost-imports",
  "DELETE /v1/cost-imports/domain-rules/:ruleId": "cost-imports",
  "POST /v1/cost-imports/reconcile": "cost-imports",
  "GET /v1/cost-imports/reconciliation": "cost-imports",
  "POST /v1/cost-imports/roster": "cost-imports",
  "DELETE /v1/cost-imports/:importId": "cost-imports",
  "GET /v1/cost-imports/:importId": "cost-imports",
  "GET /v1/costs/unattributed": "costs",
  "GET /v1/custom-model-providers": "custom-model-providers",
  "POST /v1/custom-model-providers": "custom-model-providers",
  "DELETE /v1/custom-model-providers/:providerId": "custom-model-providers",
  "PATCH /v1/custom-model-providers/:providerId": "custom-model-providers",
  "POST /v1/custom-model-providers/:providerId/enabled": "custom-model-providers",
  "POST /v1/custom-model-providers/:providerId/test": "custom-model-providers",
  "GET /v1/decisions": "decisions",
  "POST /v1/decisions": "decisions",
  "GET /v1/delegations": "delegations",
  "POST /v1/delegations": "delegations",
  "DELETE /v1/delegations/:delegationId": "delegations",
  "GET /v1/deploy/targets": "deploy",
  "POST /v1/deploy/targets": "deploy",
  "DELETE /v1/deploy/targets/:name": "deploy",
  "GET /v1/egress-allow-hosts": "egress-allow-hosts",
  "POST /v1/egress-allow-hosts": "egress-allow-hosts",
  "DELETE /v1/egress-allow-hosts/:hostId": "egress-allow-hosts",
  "GET /v1/evals/datasets": "evals",
  "POST /v1/evals/datasets": "evals",
  "GET /v1/evals/datasets/:id": "evals",
  "POST /v1/evals/datasets/:id/cases": "evals",
  "DELETE /v1/evals/datasets/:id/cases/:caseId": "evals",
  "POST /v1/evals/datasets/:id/versions": "evals",
  "GET /v1/evals/runs": "evals",
  "POST /v1/evals/runs": "evals",
  "GET /v1/evals/runs/:id": "evals",
  "POST /v1/evals/runs/:id/baseline": "evals",
  "GET /v1/evals/scorers": "evals",
  "GET /v1/evals/scoring-semantics": "evals",
  "GET /v1/evals/summary": "evals",
  // ADR-0088 — registered external eval scorers
  "GET /v1/external-scorers": "external-scorers",
  "POST /v1/external-scorers": "external-scorers",
  "PATCH /v1/external-scorers/:scorerId": "external-scorers",
  "DELETE /v1/external-scorers/:scorerId": "external-scorers",
  "POST /v1/external-scorers/:scorerId/test": "external-scorers",
  "POST /v1/external-scorers/:scorerId/enabled": "external-scorers",
  "POST /v1/authz/check": "evaluate",
  "POST /v1/evaluate": "evaluate",
  "GET /v1/git/connections": "git",
  "POST /v1/git/connections": "git",
  "POST /v1/grants/agents": "grants",
  "DELETE /v1/grants/agents/:grantId": "grants",
  "POST /v1/grants/connectors": "grants",
  "DELETE /v1/grants/connectors/:grantId": "grants",
  "POST /v1/grants/servers": "grants",
  "POST /v1/grants/tools": "grants",
  // ADR-0090 — the direct MCP grant deletes + certification campaigns
  "DELETE /v1/grants/tools/:grantId": "grants",
  "DELETE /v1/grants/servers/:grantId": "grants",
  "POST /v1/certification-campaigns": "certification",
  "POST /v1/certification-campaigns/preview": "certification",
  "GET /v1/certification-campaigns": "certification",
  "GET /v1/certification-campaigns/:campaignId": "certification",
  "POST /v1/certification-campaigns/expiry-sweep": "certification",
  "POST /v1/certification-campaigns/:campaignId/items/:itemId/reassign": "certification",
  // ADR-0091 — toxic-combination SoD rules + override escalations
  "POST /v1/sod/rules": "sod",
  "GET /v1/sod/rules": "sod",
  "PATCH /v1/sod/rules/:ruleId": "sod",
  "DELETE /v1/sod/rules/:ruleId": "sod",
  "POST /v1/sod/overrides": "sod",
  "GET /v1/sod/overrides": "sod",
  "GET /v1/group-role-mappings": "group-role-mappings",
  "POST /v1/group-role-mappings": "group-role-mappings",
  "DELETE /v1/group-role-mappings/:mappingId": "group-role-mappings",
  "GET /v1/group-role-mappings/asserted-groups": "group-role-mappings",
  "GET /v1/guardrails/config": "guardrails",
  "PUT /v1/guardrails/config": "guardrails",
  "DELETE /v1/guardrails/config/:scope/:scopeId": "guardrails",
  "PUT /v1/guardrails/config/:scope/:scopeId": "guardrails",
  "GET /v1/guardrails/detectors": "guardrails",
  "GET /v1/guardrails/effective": "guardrails",
  "POST /v1/guardrails/sample": "guardrails",
  "GET /v1/guardrails/violations": "guardrails",
  "GET /v1/health/schedulers": "health",
  "GET /v1/infra/backups": "infra",
  "POST /v1/infra/backups/:backupId/restore": "infra",
  "GET /v1/infra/certs": "infra",
  "POST /v1/infra/certs/:certId/rotate": "infra",
  "GET /v1/infra/certs/:certId/rotations": "infra",
  "GET /v1/infra/findings": "infra",
  "POST /v1/infra/findings/:findingId/remediate": "infra",
  "GET /v1/infra/patches": "infra",
  "POST /v1/infra/patches/:patchId/apply": "infra",
  "GET /v1/infra/policies": "infra",
  "POST /v1/infra/policies": "infra",
  "GET /v1/infra/posture": "infra",
  "GET /v1/infra/resources": "infra",
  "POST /v1/infra/resources": "infra",
  "POST /v1/infra/scan": "infra",
  "GET /v1/initiatives": "initiatives",
  "POST /v1/initiatives": "initiatives",
  "DELETE /v1/initiatives/:initiativeId": "initiatives",
  "GET /v1/initiatives/:initiativeId": "initiatives",
  "PATCH /v1/initiatives/:initiativeId": "initiatives",
  "GET /v1/interception/effective": "interception",
  "GET /v1/interception/scope-rules": "interception",
  "POST /v1/interception/scope-rules": "interception",
  "DELETE /v1/interception/scope-rules/:ruleId": "interception",
  "PATCH /v1/interception/scope-rules/:ruleId": "interception",
  "GET /v1/interception/settings": "interception",
  "PUT /v1/interception/settings": "interception",
  "GET /v1/keys": "keys",
  "POST /v1/keys/:keyId/revoke": "keys",
  "GET /v1/licenses": "licenses",
  "POST /v1/licenses": "licenses",
  "GET /v1/licenses/:id": "licenses",
  "GET /v1/licenses/status": "licenses",
  "GET /v1/licenses/verifications": "licenses",
  "POST /v1/licenses/verify": "licenses",
  "GET /v1/llm/backends": "regulait-llm",
  "PUT /v1/llm/backend-configs/:backend": "regulait-llm",
  "DELETE /v1/llm/backend-configs/:backend": "regulait-llm",
  "GET /v1/llm/datasets": "regulait-llm",
  "POST /v1/llm/datasets": "regulait-llm",
  "GET /v1/llm/datasets/:id": "regulait-llm",
  "POST /v1/llm/datasets/:id/rows": "regulait-llm",
  "POST /v1/llm/datasets/:id/versions": "regulait-llm",
  "POST /v1/llm/datasets/:id/validate": "regulait-llm",
  "GET /v1/llm/jobs": "regulait-llm",
  "POST /v1/llm/jobs": "regulait-llm",
  "GET /v1/llm/jobs/:id": "regulait-llm",
  "POST /v1/llm/jobs/:id/cancel": "regulait-llm",
  "POST /v1/llm/jobs/:id/poll": "regulait-llm",
  "POST /v1/llm/jobs/poll-sweep": "regulait-llm",
  "GET /v1/llm/artifacts": "regulait-llm",
  "GET /v1/llm/artifacts/:id": "regulait-llm",
  "POST /v1/llm/artifacts/:id/query": "regulait-llm",
  "POST /v1/llm/artifacts/:id/register": "regulait-llm",
  "GET /v1/lineage": "lineage",
  "GET /v1/lineage/nodes": "lineage",
  "GET /v1/lineage/overview": "lineage",
  "GET /v1/lineage/runs/:runId": "lineage",
  "GET /v1/me": "me",
  "POST /v1/messages": "messages",
  "GET /v1/model-credentials": "model-credentials",
  "POST /v1/model-credentials": "model-credentials",
  "DELETE /v1/model-credentials/:provider": "model-credentials",
  "GET /v1/model-providers/status": "model-providers",
  "GET /v1/models": "models",
  "GET /v1/mrm/cards": "mrm",
  "POST /v1/mrm/cards": "mrm",
  "DELETE /v1/mrm/cards/:id": "mrm",
  "GET /v1/mrm/cards/:id": "mrm",
  "PATCH /v1/mrm/cards/:id": "mrm",
  "POST /v1/mrm/cards/:id/evidence": "mrm",
  "DELETE /v1/mrm/cards/:id/evidence/:evidenceId": "mrm",
  "POST /v1/mrm/cards/:id/revoke": "mrm",
  "POST /v1/mrm/cards/:id/sign-off": "mrm",
  "POST /v1/mrm/enforcement": "mrm",
  "GET /v1/mrm/expiring": "mrm",
  "POST /v1/mrm/expiry-sweep": "mrm",
  "GET /v1/mrm/status": "mrm",
  "GET /v1/onboarding": "onboarding",
  "POST /v1/onboarding/compliance-pack": "onboarding",
  "GET /v1/onboarding/export": "onboarding",
  "GET /v1/onboarding/imports": "onboarding",
  "POST /v1/onboarding/imports/group-roles": "onboarding",
  "POST /v1/onboarding/imports/users": "onboarding",
  "POST /v1/onboarding/roles/seed": "onboarding",
  "POST /v1/onboarding/steps/:stepKey": "onboarding",
  "GET /v1/openapi.json": "openapi.json",
  "GET /v1/org/posture": "org",
  "POST /v1/org/posture/harden": "org",
  "GET /v1/org/settings": "org",
  "PUT /v1/org/settings": "org",
  "GET /v1/pm/connections": "pm",
  "POST /v1/pm/connections": "pm",
  "GET /v1/pm/links": "pm",
  "POST /v1/pm/webhooks/:connectionName": "pm",
  "GET /v1/projects": "projects",
  "POST /v1/projects": "projects",
  "PATCH /v1/projects/:projectId": "projects",
  "POST /v1/projects/:projectId/classifications": "projects",
  "GET /v1/projects/:projectId/compliance": "projects",
  "GET /v1/projects/:projectId/context": "projects",
  "POST /v1/projects/:projectId/context": "projects",
  "GET /v1/projects/:projectId/context/graph": "projects",
  "POST /v1/projects/:projectId/context/promote": "projects",
  "GET /v1/projects/:projectId/costs": "projects",
  "GET /v1/projects/:projectId/costs.csv": "projects",
  "GET /v1/projects/:projectId/members": "projects",
  "POST /v1/projects/:projectId/members": "projects",
  "DELETE /v1/projects/:projectId/members/:userId": "projects",
  "PATCH /v1/projects/:projectId/members/:userId": "projects",
  "GET /v1/inventory/agents": "inventory",
  "GET /v1/inventory/agents/:agentId": "inventory",
  "GET /v1/agents/:agentId/card": "inventory",
  "GET /v1/inventory/graph": "inventory",
  "GET /v1/run-graph/builder-turn/:threadId/:turn": "tracing",
  "GET /v1/run-graph/orchestration/:runId": "tracing",
  "GET /v1/run-graph/use-case/:useCaseId": "tracing",
  "GET /v1/governance/alerts": "reports",
  "GET /v1/admin/credentials": "reports",
  "GET /v1/energy/factors": "reports",
  "PUT /v1/energy/factors": "reports",
  "DELETE /v1/energy/factors/:factorId": "reports",
  "GET /v1/energy/estimate": "reports",
  "GET /v1/regulatory/updates": "reports",
  "GET /v1/governance/alerts/:alertId/remediation": "reports",
  "POST /v1/governance/alerts/:alertId/remediation": "reports",
  "GET /v1/governance/remediations": "reports",
  "GET /v1/governance/trace-evaluations": "reports",
  "POST /v1/governance/trace-evaluations/run": "reports",
  "POST /v1/gates/deploy": "use-cases",
  "PATCH /v1/chatops/connections/:connectionId": "chatops",
  "POST /v1/governance/alerts/:alertId/post": "reports",
  "POST /v1/governance/monitor/evaluate": "reports",
  "POST /v1/governance/alerts/:alertId/acknowledge": "reports",
  // ADR-0092 — access recommendations (the deterministic half)
  "GET /v1/recommendations/access": "recommendations",
  "GET /v1/reports/definitions": "reports",
  "POST /v1/reports/definitions": "reports",
  "DELETE /v1/reports/definitions/:id": "reports",
  "GET /v1/reports/definitions/:id": "reports",
  "POST /v1/reports/definitions/:id/generate": "reports",
  "POST /v1/reports/definitions/:id/schedules": "reports",
  "GET /v1/reports/overview": "reports",
  "GET /v1/reports/posture": "reports",
  "GET /v1/reports/trust": "reports",
  "GET /v1/reports/runs": "reports",
  "GET /v1/reports/runs/:id": "reports",
  "GET /v1/reports/runs/:id/export": "reports",
  "GET /v1/reports/schedules": "reports",
  "DELETE /v1/reports/schedules/:id": "reports",
  "PATCH /v1/reports/schedules/:id": "reports",
  "POST /v1/reports/schedules/run-due": "reports",
  "GET /v1/redteam/attack-classes": "redteam",
  "GET /v1/redteam/findings": "redteam",
  "GET /v1/redteam/libraries": "redteam",
  "POST /v1/redteam/libraries": "redteam",
  "POST /v1/redteam/libraries/seed": "redteam",
  "GET /v1/redteam/libraries/:id": "redteam",
  "POST /v1/redteam/libraries/:id/probes": "redteam",
  "POST /v1/redteam/libraries/:id/publish": "redteam",
  "POST /v1/redteam/libraries/:id/versions": "redteam",
  "GET /v1/redteam/runs": "redteam",
  "POST /v1/redteam/runs": "redteam",
  "GET /v1/redteam/runs/:id": "redteam",
  "GET /v1/redteam/runs/:id/trials": "redteam",
  "POST /v1/redteam/runs/:id/evidence": "redteam",
  "GET /v1/redteam/summary": "redteam",
  "GET /v1/risks": "risks",
  "POST /v1/risks": "risks",
  "GET /v1/risks/library": "risks",
  "GET /v1/risks/scenarios": "risks",
  "GET /v1/risks/:riskId": "risks",
  "PATCH /v1/risks/:riskId": "risks",
  "POST /v1/risks/:riskId/transition": "risks",
  "POST /v1/risks/:riskId/accept": "risks",
  "PUT /v1/risks/:riskId/residual": "risks",
  "POST /v1/risks/:riskId/controls": "risks",
  "DELETE /v1/risks/:riskId/controls/:controlRef": "risks",
  "POST /v1/policy-simulations": "policy-simulation",
  "GET /v1/policy-simulations": "policy-simulation",
  "GET /v1/policy-simulations/:id": "policy-simulation",
  "GET /v1/policy-simulations/settings": "policy-simulation",
  "PUT /v1/policy-simulations/settings": "policy-simulation",
  "GET /v1/revocations": "revocations",
  "POST /v1/revocations": "revocations",
  "PATCH /v1/revocations/:kind/:revocationId/scope": "revocations",
  "DELETE /v1/revocations/:revocationId": "revocations",
  "GET /v1/roles": "roles",
  "POST /v1/roles": "roles",
  "DELETE /v1/roles/:roleId": "roles",
  "GET /v1/roles/:roleId/assignments": "roles",
  "GET /v1/roles/:roleId/grants": "roles",
  "POST /v1/roles/:roleId/grants/agents": "roles",
  "DELETE /v1/roles/:roleId/grants/agents/:grantId": "roles",
  "POST /v1/roles/:roleId/grants/connectors": "roles",
  "DELETE /v1/roles/:roleId/grants/connectors/:grantId": "roles",
  "POST /v1/roles/:roleId/grants/servers": "roles",
  "DELETE /v1/roles/:roleId/grants/servers/:grantId": "roles",
  "POST /v1/roles/:roleId/grants/tools": "roles",
  "DELETE /v1/roles/:roleId/grants/tools/:grantId": "roles",
  "PATCH /v1/rules/:kind/:ruleId/deploy-mode": "rules",
  "PATCH /v1/rules/:kind/:ruleId": "rules",
  "DELETE /v1/rules/:kind/:ruleId": "rules",
  "GET /v1/rules/approvals": "rules",
  "POST /v1/rules/approvals": "rules",
  "GET /v1/rules/data-scopes": "rules",
  "POST /v1/rules/data-scopes": "rules",
  "GET /v1/rules/rate-limits": "rules",
  "POST /v1/rules/rate-limits": "rules",
  "GET /v1/runs": "runs",
  "POST /v1/runs": "runs",
  "GET /v1/runs/:runId": "runs",
  "POST /v1/runs/:runId/auto": "runs",
  "POST /v1/runs/:runId/events": "runs",
  "POST /v1/runs/:runId/nodes/:nodeId/dispatch": "runs",
  "POST /v1/runs/:runId/pm-sync": "runs",
  "POST /v1/runs/decompose": "runs",
  "GET /v1/scim/status": "scim",
  "GET /v1/scim/tokens": "scim",
  "POST /v1/scim/tokens": "scim",
  "POST /v1/scim/tokens/:tokenId/revoke": "scim",
  "POST /v1/scim/tokens/:tokenId/rotate": "scim",
  "GET /v1/servers": "servers",
  "POST /v1/servers": "servers",
  "PATCH /v1/servers/:serverId": "servers",
  "GET /v1/servers/:serverId/tools": "servers",
  "POST /v1/servers/:serverId/tools": "servers",
  "GET /v1/mcp/admission": "servers",
  "POST /v1/mcp-registries": "servers",
  "GET /v1/mcp-registries": "servers",
  "PATCH /v1/mcp-registries/:registryId": "servers",
  "POST /v1/mcp-registries/:registryId/sync": "servers",
  "GET /v1/mcp-registries/:registryId/entries": "servers",
  "POST /v1/mcp-registries/entries/:entryId/import": "servers",
  "POST /v1/servers/:serverId/admission/clear": "servers",
  "GET /v1/admission/skills": "builder",
  "POST /v1/admission/skills/:id/admit": "builder",
  "POST /v1/admission/skills/:id/visibility": "builder",
  "GET /v1/release-quarantine": "servers",
  "POST /v1/release-quarantine/override": "servers",
  "PATCH /v1/servers/:serverId/tools/:toolName/price": "servers",
  "GET /v1/setup/status": "setup",
  "GET /v1/security/data-key": "security",
  "GET /v1/security/data-key/attestations": "security",
  "POST /v1/security/data-key/attestations": "security",
  "GET /v1/security/data-key/reencryption": "security",
  "GET /v1/scheduler": "scheduler",
  "GET /v1/scheduler/jobs/:name/runs": "scheduler",
  "PATCH /v1/scheduler/jobs/:name": "scheduler",
  "POST /v1/scheduler/jobs/:name/run": "scheduler",
  "POST /v1/evals/drift-sweep": "evals",
  "POST /v1/redteam/scheduled-sweep": "redteam",
  "GET /v1/chatops/connections": "chatops",
  "POST /v1/chatops/connections": "chatops",
  "DELETE /v1/chatops/connections/:connectionId": "chatops",
  "GET /v1/chatops/identity-links": "chatops",
  "POST /v1/chatops/identity-links": "chatops",
  "DELETE /v1/chatops/identity-links/:linkId": "chatops",
  "POST /v1/chatops/approvals/:approvalId/post": "chatops",
  "POST /v1/chatops/:connectionName/interactions": "chatops",
  "POST /v1/chatops/:connectionName/events": "chatops",
  "POST /v1/chatops/:connectionName/messages": "chatops",
  "POST /v1/chatops/:connectionName/bot": "chatops",
  "GET /v1/chatops/builder-routes": "chatops",
  "PUT /v1/chatops/builder-routes/:channelId": "chatops",
  "GET /v1/builder/agents": "builder",
  "POST /v1/builder/agents": "builder",
  "POST /v1/builder/agents/import": "builder",
  "GET /v1/builder/agents/:id": "builder",
  "PATCH /v1/builder/agents/:id": "builder",
  "DELETE /v1/builder/agents/:id": "builder",
  "PUT /v1/builder/agents/:id/tools": "builder",
  "PUT /v1/builder/agents/:id/subagents": "builder",
  "PUT /v1/builder/agents/:id/skills": "builder",
  "POST /v1/builder/agents/:id/skills/:skillId/reattach": "builder",
  "POST /v1/builder/agents/:id/memory": "builder",
  "DELETE /v1/builder/agents/:id/memory/:memoryId": "builder",
  "POST /v1/builder/agents/:id/schedules": "builder",
  "PATCH /v1/builder/agents/:id/schedules/:scheduleId": "builder",
  "DELETE /v1/builder/agents/:id/schedules/:scheduleId": "builder",
  "POST /v1/builder/agents/:id/channels": "builder",
  "DELETE /v1/builder/agents/:id/channels/:channelId": "builder",
  "GET /v1/builder/agents/:id/export": "builder",
  "POST /v1/builder/agents/:id/chat": "builder",
  "POST /v1/builder/schedules/sweep": "builder",
  "GET /v1/builder/threads": "builder",
  "GET /v1/builder/threads/:id": "builder",
  "PATCH /v1/builder/threads/:id": "builder",
  "POST /v1/builder/threads/:id/steps/:stepId/confirm": "builder",
  "POST /v1/builder/threads/:id/steps/:stepId/cancel": "builder",
  "GET /v1/builder/skills": "builder",
  "POST /v1/builder/skills": "builder",
  "POST /v1/builder/skills/import": "builder",
  "GET /v1/builder/skills/:id": "builder",
  "PATCH /v1/builder/skills/:id": "builder",
  "DELETE /v1/builder/skills/:id": "builder",
  "GET /v1/builder/templates": "builder",
  "GET /v1/builder/templates/:id": "builder",
  "GET /v1/builder/integrations": "builder",
  "GET /v1/builder/toolbox-options": "builder",
  "GET /v1/builder/usage": "builder",
  "GET /v1/copilot/tools": "copilot",
  "POST /v1/copilot/ask": "copilot",
  "GET /v1/copilot/queries": "copilot",
  "POST /v1/copilot/proposals": "copilot",
  "GET /v1/copilot/proposals": "copilot",
  "POST /v1/copilot/proposals/:proposalId/apply": "copilot",
  "GET /v1/compliance/packs": "compliance-packs",
  "POST /v1/compliance/packs": "compliance-packs",
  "POST /v1/compliance/packs/seed": "compliance-packs",
  "GET /v1/compliance/packs/:id": "compliance-packs",
  "POST /v1/compliance/packs/:id/activate": "compliance-packs",
  "DELETE /v1/compliance/packs/:id": "compliance-packs",
  "POST /v1/compliance/packs/:id/attestations": "compliance-packs",
  "POST /v1/compliance/packs/:id/evaluate": "compliance-packs",
  "GET /v1/compliance/pack-reports": "compliance-packs",
  "GET /v1/compliance/pack-reports/:id": "compliance-packs",
  "GET /v1/compliance-packs/:framework/diff": "compliance-packs",
  "GET /v1/shadow-ai/catalogue": "shadow-ai",
  "POST /v1/shadow-ai/catalogue": "shadow-ai",
  "POST /v1/shadow-ai/catalogue/seed": "shadow-ai",
  "DELETE /v1/shadow-ai/catalogue/:signatureId": "shadow-ai",
  "GET /v1/shadow-ai/findings": "shadow-ai",
  "POST /v1/shadow-ai/findings/:findingId/disposition": "shadow-ai",
  "POST /v1/shadow-ai/findings/:findingId/remediate": "shadow-ai",
  "GET /v1/shadow-ai/findings/:findingId/remediation-plan": "shadow-ai",
  "GET /v1/shadow-ai/imports": "shadow-ai",
  "POST /v1/shadow-ai/imports": "shadow-ai",
  "GET /v1/shadow-ai/adapters": "shadow-ai",
  "POST /v1/shadow-ai/imports/raw": "shadow-ai",
  "GET /v1/shadow-ai/discovery/catalog": "shadow-ai",
  "POST /v1/shadow-ai/discovery": "shadow-ai",
  "POST /v1/shadow-ai/mcp-discovery": "shadow-ai",
  "GET /v1/spend/anomalies": "spend",
  "PATCH /v1/spend/anomalies/:id": "spend",
  "POST /v1/spend/anomalies/evaluate": "spend",
  "GET /v1/spend/forecast": "spend",
  "GET /v1/spend/monitor-overview": "spend",
  "GET /v1/spend/monitor-policies": "spend",
  "PUT /v1/spend/monitor-policies": "spend",
  "GET /v1/spend/scheduled-changes": "spend",
  "POST /v1/spend/scheduled-changes": "spend",
  "DELETE /v1/spend/scheduled-changes/:id": "spend",
  "GET /v1/teams": "teams",
  "POST /v1/teams": "teams",
  "DELETE /v1/teams/:teamId": "teams",
  "POST /v1/teams/:teamId/members": "teams",
  "DELETE /v1/teams/:teamId/members/:userId": "teams",
  "GET /v1/usage-events": "usage-events",
  "GET /v1/use-cases": "use-cases",
  "POST /v1/use-cases": "use-cases",
  "POST /v1/use-cases/intake/assist": "use-cases",
  "GET /v1/use-cases/:useCaseId/overview": "use-cases",
  "GET /v1/use-cases/:useCaseId": "use-cases",
  "GET /v1/use-cases/:useCaseId/frameworks": "use-cases",
  "GET /v1/use-cases/draft": "use-cases",
  "PUT /v1/use-cases/draft": "use-cases",
  "DELETE /v1/use-cases/draft": "use-cases",
  "GET /v1/execution": "org-settings",
  "GET /v1/model-policy": "agents",
  "PUT /v1/model-policy": "agents",
  "GET /v1/prompts": "prompts",
  "POST /v1/prompts": "prompts",
  "GET /v1/prompts/resolve": "prompts",
  "GET /v1/prompts/:promptId": "prompts",
  "PATCH /v1/prompts/:promptId": "prompts",
  "DELETE /v1/prompts/:promptId": "prompts",
  "POST /v1/prompts/:promptId/commits": "prompts",
  "GET /v1/prompts/:promptId/commits/:hash": "prompts",
  "GET /v1/prompts/:promptId/diff": "prompts",
  "PUT /v1/prompts/:promptId/tags/:tag": "prompts",
  "POST /v1/playground/run": "playground",
  "POST /v1/playground/evaluate": "playground",
  "GET /v1/webhooks/events": "webhooks",
  "GET /v1/webhooks": "webhooks",
  "POST /v1/webhooks": "webhooks",
  "PATCH /v1/webhooks/:subscriptionId": "webhooks",
  "DELETE /v1/webhooks/:subscriptionId": "webhooks",
  "POST /v1/webhooks/:subscriptionId/rotate-secret": "webhooks",
  "POST /v1/webhooks/:subscriptionId/test": "webhooks",
  "GET /v1/webhooks/:subscriptionId/deliveries": "webhooks",
  "POST /v1/webhooks/deliveries/:deliveryId/retry": "webhooks",
  "POST /v1/webhooks/sweep": "webhooks",
  // ADR-0173 batch 2c (E)
  "GET /v1/evals/catalog": "evals",
  "GET /v1/evals/catalog/tested-by": "evals",
  "POST /v1/evals/datasets/:id/from-traces": "evals",
  "POST /v1/evals/traces/evaluate": "evals",
  "GET /v1/evals/compare": "evals",
  "POST /v1/evals/runs/:id/calibration": "evals",
  "PUT /v1/execution/mode": "org-settings",
  "POST /v1/agents/:agentId/halt": "agents",
  "POST /v1/agents/:agentId/unhalt": "agents",
  "POST /v1/servers/:serverId/tools/:toolName/halt": "servers",
  "POST /v1/servers/:serverId/tools/:toolName/unhalt": "servers",
  "PATCH /v1/use-cases/:useCaseId": "use-cases",
  "POST /v1/use-cases/:useCaseId/retire": "use-cases",
  "POST /v1/use-cases/:useCaseId/conditions/:conditionId/met": "use-cases",
  "GET /v1/governance/review-policy": "use-cases",
  "PUT /v1/governance/review-policy": "use-cases",
  "POST /v1/governance/recertification/sweep": "use-cases",
  "GET /v1/vendors": "vendors",
  "POST /v1/vendors": "vendors",
  "GET /v1/vendors/:vendorId": "vendors",
  "PATCH /v1/vendors/:vendorId": "vendors",
  "POST /v1/vendors/:vendorId/attestations": "vendors",
  "POST /v1/vendors/:vendorId/retire": "vendors",
  "GET /v1/users": "users",
  "POST /v1/users": "users",
  "PATCH /v1/users/:userId": "users",
  "POST /v1/users/:userId/admin": "users",
  "POST /v1/users/:userId/agent-policy": "users",
  "GET /v1/users/:userId/agents": "users",
  "GET /v1/users/:userId/connectors": "users",
  "GET /v1/users/:userId/cost-consolidated": "cost-imports",
  "PUT /v1/users/:userId/cost-center": "cost-imports",
  "POST /v1/users/:userId/deactivate": "users",
  "POST /v1/users/:userId/keys": "users",
  "POST /v1/users/:userId/mfa/clear": "users",
  "GET /v1/users/:userId/model-credentials": "users",
  "POST /v1/users/:userId/model-credentials": "users",
  "DELETE /v1/users/:userId/model-credentials/:provider": "users",
  "POST /v1/users/:userId/reactivate": "users",
  "GET /v1/users/:userId/revocations/agents": "users",
  "POST /v1/users/:userId/revocations/agents": "users",
  "DELETE /v1/users/:userId/revocations/agents/:revocationId": "users",
  "GET /v1/users/:userId/revocations/connectors": "users",
  "POST /v1/users/:userId/revocations/connectors": "users",
  "DELETE /v1/users/:userId/revocations/connectors/:revocationId": "users",
  "GET /v1/users/:userId/role-provenance": "users",
  "POST /v1/users/:userId/roles": "users",
  "DELETE /v1/users/:userId/roles/:roleId": "users",
  "GET /v1/users/:userId/servers/:serverId/entitlements": "users",
  "GET /v1/users/:userId/servers/:serverId/tools": "users",
  "GET /v1/users/:userId/sessions": "users",
  "POST /v1/users/:userId/sessions/:sessionId/revoke": "users",
  "POST /v1/users/:userId/sessions/revoke": "users",
  "POST /v1/users/:userId/set-initial-password": "users",
  "PUT /v1/users/:userId/username": "users",
  "GET /v1/users/directory": "users",
  "GET /v1/virtual-keys": "virtual-keys",
  "POST /v1/virtual-keys": "virtual-keys",
  "PATCH /v1/virtual-keys/:keyId": "virtual-keys",
  "DELETE /v1/virtual-keys/:keyId": "virtual-keys",
  "GET /v1/virtual-keys/:keyId/usage": "virtual-keys",
  "GET /v1/workflows/assignment-rules": "workflows",
  "POST /v1/workflows/assignment-rules": "workflows",
  "DELETE /v1/workflows/assignment-rules/:ruleId": "workflows",
  "GET /v1/workflows/instances": "workflows",
  "POST /v1/workflows/instances": "workflows",
  "GET /v1/workflows/instances/:instanceId": "workflows",
  "POST /v1/workflows/instances/:instanceId/abort": "workflows",
  "POST /v1/workflows/instances/:instanceId/advance": "workflows",
  "POST /v1/workflows/instances/:instanceId/artifacts": "workflows",
  "POST /v1/workflows/instances/:instanceId/checks": "workflows",
  "POST /v1/workflows/instances/:instanceId/deploy-override": "workflows",
  "POST /v1/workflows/instances/:instanceId/pm-sync": "workflows",
  "POST /v1/workflows/instances/:instanceId/recheck": "workflows",
  "GET /v1/workflows/template-gallery": "workflows",
  "POST /v1/workflows/template-gallery/:galleryId/create": "workflows",
  "GET /v1/workflows/templates": "workflows",
  "POST /v1/workflows/templates": "workflows",
  "POST /v1/workflows/templates/:templateId/retire": "workflows",
};
