// Licence inventory for the spike's exact npm closure (pattern of spikes/identity-s0/licences.mjs).
// `node licences.mjs` checks THIRD_PARTY.md and licence-inventory.json against the installed lock; `--write`
// regenerates them. Requires `npm ci --ignore-scripts` first. Also records the vendored SPDX files.
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root = path.dirname(fileURLToPath(import.meta.url));
const digest = (s) => createHash('sha256').update(s).digest('hex');
const lockBytes = await readFile(path.join(root, 'package-lock.json'));
const lock = JSON.parse(lockBytes);
const allowed = new Set(['MIT', 'ISC', 'BSD-2-Clause', 'BSD-3-Clause', '0BSD', 'Apache-2.0']);
const rows = [];
const texts = [];
for (const [location, entry] of Object.entries(lock.packages)) {
  if (!location) continue;
  assert.ok(!entry.dev, `unexpected development package ${location}`);
  const folder = path.join(root, location);
  const pkg = JSON.parse(await readFile(path.join(folder, 'package.json')));
  assert.equal(pkg.version, entry.version);
  assert.ok(allowed.has(pkg.license), `unadmitted ${pkg.name}: ${pkg.license}`);
  const files = (await readdir(folder)).filter((f) => /^(licen[cs]e|copying|notice)(\.|$)/i.test(f)).sort();
  assert.ok(files.length, `missing licence text ${pkg.name}`);
  const text = (await Promise.all(files.map((f) => readFile(path.join(folder, f), 'utf8')))).join('\n');
  assert.ok(/permission|redistribution|copyright|apache license/i.test(text), `empty notice ${pkg.name}`);
  rows.push({ name: pkg.name, version: pkg.version, location, licence: pkg.license, resolved: entry.resolved,
    integrity: entry.integrity, noticeSource: files.join(', '), noticeSha256: digest(text) });
  texts.push(`\n## ${pkg.name} ${pkg.version} (${pkg.license})\n\nSource: ${files.join(', ')}\n\n${text.trim()}\n`);
}
rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
const vendored = [];
for (const [file, url] of [
  ['schemas/spdx-3.0.1-json-schema.json', 'https://spdx.org/schema/3.0.1/spdx-json-schema.json'],
  ['schemas/spdx-3.0.1-model.ttl', 'https://spdx.org/rdf/3.0.1/spdx-model.ttl'],
  ['schemas/spdx-3.0.1-context.jsonld', 'https://spdx.org/rdf/3.0.1/spdx-context.jsonld'],
]) vendored.push({ file, source: url, fetched: '2026-10-10', sha256: digest(await readFile(path.join(root, file))) });
const inventory = JSON.stringify({ lockSha256: digest(lockBytes), packages: rows, vendored }, null, 2) + '\n';
const header = [
  '# BOM B0 spike dependency notices',
  '',
  'Generated by `licences.mjs` from the exact installed npm lock; upstream text retained verbatim.',
  '',
  '| Package | Version | Licence | Integrity |',
  '|---|---|---|---|',
  ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.licence} | \`${r.integrity}\` |`),
  '',
  '## Vendored SPDX 3.0.1 files (data, not code)',
  '',
  'Fetched 2026-10-10 from spdx.org (served by the specification site). The SPDX 3.0.1 specification site lists the',
  'Community Specification License 1.0 and CC-BY-3.0 for the specification; neither is on ADR-0176\'s code-licence list,',
  'which is an open point for B5 (R12 §2). The CycloneDX schemas are not vendored here: they ship inside',
  '`@cyclonedx/cyclonedx-library` (Apache-2.0).',
  '',
  '| File | Source | sha256 |',
  '|---|---|---|',
  ...vendored.map((v) => `| \`${v.file}\` | ${v.source} | \`${v.sha256}\` |`),
  '',
  '## CI-only Python closure (spdx3/requirements.lock, never shipped)',
  '',
  'spdx3-validate 0.0.7 (MIT) and 22 dependencies, hash-pinned. Licences per package metadata: MIT (13),',
  'BSD-3-Clause/BSD (3: rdflib, prettytable, colorama), Apache-2.0 (2: pyshacl, importlib_metadata),',
  'Apache-2.0 OR BSD-2-Clause (packaging), PSF-2.0 (typing_extensions), W3C-20150513 (owlrl). PSF-2.0 and W3C are',
  'permissive but outside ADR-0176\'s list; acceptable only because this closure is CI tooling, never shipped.',
  '',
].join('\n');
const notices = `${header}${texts.join('\n')}`;
if (process.argv.includes('--write')) {
  await writeFile(path.join(root, 'licence-inventory.json'), inventory);
  await writeFile(path.join(root, 'THIRD_PARTY.md'), notices);
} else {
  assert.equal(await readFile(path.join(root, 'licence-inventory.json'), 'utf8'), inventory, 'inventory drift');
  assert.equal(await readFile(path.join(root, 'THIRD_PARTY.md'), 'utf8'), notices, 'notice drift');
}
const counts = {};
for (const r of rows) counts[r.licence] = (counts[r.licence] ?? 0) + 1;
process.stdout.write(JSON.stringify({ runtimePackages: rows.length, licences: counts, lockSha256: digest(lockBytes) }) + '\n');
