# ADR-0029: the app is served over HTTPS at the sslip.io name derived from the
# instance's public IP. Plain http://<ip>:3000 no longer answers from off-box.
output "app_url" {
  value = "https://${module.app.sslip_hostname}"
}

output "tls_hostname" {
  value = module.app.sslip_hostname
}

output "public_ip" {
  value = module.app.public_ip
}

output "instance_id" {
  value = module.app.instance_id
}

output "source_bucket" {
  value = module.app.source_bucket
}

# --- scheduled power (ADR-0032) ----------------------------------------------

output "public_ip_is_stable" {
  description = "True once the Elastic IP is attached. If this is ever false while power_schedule is enabled, the sslip.io hostname and its certificate will break on the next stop/start."
  value       = module.app.public_ip_is_stable
}

output "power_window" {
  description = "The effective power schedule, in one line."
  value       = module.power_schedule.window_summary
}

output "power_schedule_names" {
  description = "EventBridge Scheduler schedule names, for one-off `aws scheduler update-schedule` overrides."
  value = {
    start = module.power_schedule.start_schedule_name
    stop  = module.power_schedule.stop_schedule_name
  }
}

# Copy-paste manual override. The box can always be started outside the window;
# it will still be stopped at the next stop-cron (see the module README).
output "manual_start_command" {
  value = "aws ec2 start-instances --instance-ids ${module.app.instance_id} --region ${var.aws_region} --profile ${var.workload_sso_profile}"
}

output "manual_stop_command" {
  value = "aws ec2 stop-instances --instance-ids ${module.app.instance_id} --region ${var.aws_region} --profile ${var.workload_sso_profile}"
}

# --- database backup (ADR-0035) ----------------------------------------------

output "backup_destination" {
  description = "Where the nightly pg_dump lands."
  value       = module.db_backup.destination_uri
}

output "backup_retention" {
  description = "The retention promise, in one line."
  value       = module.db_backup.retention_summary
}

output "backup_alarm_name" {
  description = "CloudWatch alarm that fires when the heartbeat stops."
  value       = module.db_backup.alarm_name
}

output "backup_alarm_notifies_anyone" {
  description = "FALSE means the alarm exists and turns red in the console but pages nobody. Set backup_alarm_sns_topic_arns to change that."
  value       = module.db_backup.alarm_notifies_anyone
}

# Terraform is the source of truth for the schedule and retention, so it also
# renders the on-box config file rather than leaving an operator to retype
# bucket names at 3am. `terraform output -raw backup_env_file` > the box.
output "backup_env_file" {
  description = "Exact contents of /etc/regulait-pg-backup.env for the app box."
  value = join("\n", [
    "# Generated by terraform (infra/environments/regulait-dev-app). Do not hand-edit;",
    "# change the variables and re-render with `terraform output -raw backup_env_file`.",
    "REGULAIT_BACKUP_BUCKET=${module.db_backup.bucket}",
    "REGULAIT_BACKUP_PREFIX=${module.db_backup.prefix}",
    "REGULAIT_BACKUP_REGION=${var.aws_region}",
    "REGULAIT_BACKUP_ENABLED=${var.backup_enabled ? 1 : 0}",
    "REGULAIT_BACKUP_ONCALENDAR=${var.backup_oncalendar}",
    "REGULAIT_BACKUP_METRIC_NAMESPACE=${module.db_backup.metric_namespace}",
    "REGULAIT_BACKUP_METRIC_NAME=${module.db_backup.metric_name}",
    "REGULAIT_BACKUP_METRIC_TARGET=${module.db_backup.metric_dimension_target}",
    "",
  ])
}

# One SSM command that ships the script + the rendered env file and installs the
# timer. Idempotent — re-running it is how a schedule change is applied.
output "backup_install_command" {
  description = "Copy-paste installer. Run from the repo root; see docs/ops/DB_BACKUP.md for the long form."
  value       = "bash infra/scripts/install-pg-backup.sh"
}
