/**
 * GENERATED — do not edit. ADR-0187 B5-G decision 142: garak's own probe metadata, read from the
 * pinned release's `garak/resources/plugin_cache.json` by engines/garak/extract-probe-metadata.mjs
 * (read as data, nothing executed).
 *
 * Package:  PyPI `garak==0.17.0` (wheel sha256 9a67e6298e4d7025358fecafa9d473c77ff70acdae103aa5251ad60fca3db145)
 * Source:   garak/resources/plugin_cache.json
 * sha256:   25484e2467c84b1a59e27ae7ebf433a305b00c859aa1904c315f916661134a52
 *
 * `detector` is the probe's primary detector: the only one garak runs with `extended_detectors: false`,
 * which the runner always sets. `owasp` are garak's own tags, in the 2023 OWASP LLM Top 10 numbering
 * (R10); the crosswalk to the 2025 list is in garak.ts. To update: pin a new release, re-run the
 * extractor, re-read R10.
 */
export const GARAK_UPSTREAM_VERSION = "0.17.0";
export const GARAK_UPSTREAM_SOURCE_SHA256 = "25484e2467c84b1a59e27ae7ebf433a305b00c859aa1904c315f916661134a52";

export interface GarakUpstreamProbe {
  /** `module.Class`, as garak names it in its report */
  probe: string;
  active: boolean;
  /** the primary detector, `module.Class`, or null when the probe names none */
  detector: string | null;
  /** garak's `owasp:llmNN` tags (2023 numbering) */
  owasp: readonly string[];
}

export const GARAK_UPSTREAM_PROBES: readonly GarakUpstreamProbe[] = Object.freeze([
  { probe: "adaptive_attacks.AdaptiveAttacks", active: true, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "agent_breaker.AgentBreaker", active: false, detector: "agent_breaker.AgentBreakerResult", owasp: ["owasp:llm01","owasp:llm07","owasp:llm08"] },
  { probe: "ansiescape.AnsiEscaped", active: true, detector: "ansiescape.Escaped", owasp: ["owasp:llm01","owasp:llm02","owasp:llm05"] },
  { probe: "ansiescape.AnsiRaw", active: true, detector: "ansiescape.Raw", owasp: ["owasp:llm01","owasp:llm02","owasp:llm05"] },
  { probe: "ansiescape.AnsiRawTokenizerHF", active: false, detector: "ansiescape.Raw", owasp: ["owasp:llm05"] },
  { probe: "apikey.CompleteKey", active: true, detector: "apikey.ApiKey", owasp: [] },
  { probe: "apikey.GetKey", active: true, detector: "apikey.ApiKey", owasp: [] },
  { probe: "atkgen.Tox", active: true, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "audio.AudioAchillesHeel", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "av_spam_scanning.EICAR", active: false, detector: "knownbadsignatures.EICAR", owasp: ["owasp:llm02"] },
  { probe: "av_spam_scanning.GTUBE", active: false, detector: "knownbadsignatures.GTUBE", owasp: ["owasp:llm02"] },
  { probe: "av_spam_scanning.GTphish", active: false, detector: "knownbadsignatures.GTphish", owasp: ["owasp:llm02"] },
  { probe: "badchars.BadCharacters", active: true, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "continuation.ContinueSlursReclaimedSlurs", active: true, detector: "continuation.Continuation", owasp: ["owasp:llm01"] },
  { probe: "continuation.ContinueSlursReclaimedSlursFull", active: false, detector: "continuation.Continuation", owasp: ["owasp:llm01"] },
  { probe: "dan.Ablation_Dan_11_0", active: true, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.AntiDAN", active: false, detector: "dan.AntiDAN", owasp: ["owasp:llm01"] },
  { probe: "dan.AutoDAN", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.AutoDANCached", active: true, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.ChatGPT_Developer_Mode_RANTI", active: false, detector: "dan.DevMode", owasp: ["owasp:llm01"] },
  { probe: "dan.ChatGPT_Developer_Mode_v2", active: false, detector: "dan.DevMode", owasp: ["owasp:llm01"] },
  { probe: "dan.ChatGPT_Image_Markdown", active: false, detector: "dan.MarkdownLink", owasp: ["owasp:llm01"] },
  { probe: "dan.DAN_Jailbreak", active: false, detector: "dan.DANJailbreak", owasp: ["owasp:llm01"] },
  { probe: "dan.DUDE", active: false, detector: "dan.DUDE", owasp: ["owasp:llm01"] },
  { probe: "dan.DanInTheWild", active: true, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "dan.DanInTheWildFull", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_10_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_11_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_6_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_6_2", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_7_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_8_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.Dan_9_0", active: false, detector: "dan.DAN", owasp: ["owasp:llm01"] },
  { probe: "dan.STAN", active: false, detector: "dan.STAN", owasp: ["owasp:llm01"] },
  { probe: "divergence.Repeat", active: true, detector: "divergence.RepeatDiverges", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "divergence.RepeatExtended", active: false, detector: "divergence.RepeatDiverges", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "divergence.RepeatedToken", active: true, detector: "divergence.RepeatedToken", owasp: ["owasp:llm04"] },
  { probe: "doctor.Bypass", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "doctor.BypassLeet", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "doctor.Puppetry", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "donotanswer.DiscriminationExclusionToxicityHatefulOffensive", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "donotanswer.HumanChatbox", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "donotanswer.InformationHazard", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm06"] },
  { probe: "donotanswer.MaliciousUses", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "donotanswer.MisinformationHarms", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm09"] },
  { probe: "dra.DRA", active: true, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "dra.DRAAdvanced", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectAscii85", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectAtbash", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectBase16", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectBase2048", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectBase32", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectBase64", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectBraille", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectEcoji", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectHex", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectLeet", active: false, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectMime", active: false, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectMorse", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectNato", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectQP", active: false, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectROT13", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectSneakyBits", active: false, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectUU", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectUnicodeTagChars", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectUnicodeVariantSelectors", active: false, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "encoding.InjectZalgo", active: true, detector: "encoding.DecodeMatch", owasp: ["owasp:llm01"] },
  { probe: "exploitation.JinjaTemplatePythonInjection", active: true, detector: "exploitation.JinjaTemplateInjectionDetector", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "exploitation.SQLInjectionEcho", active: true, detector: "exploitation.SQLiEcho", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "exploitation.SQLInjectionSystem", active: false, detector: "exploitation.SQLiSuccess", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "fileformats.HF_Files", active: false, detector: "fileformats.FileIsPickled", owasp: ["owasp:llm05"] },
  { probe: "fitd.FITD", active: false, detector: "judge.RefusalOnlyAdversarial", owasp: ["owasp:llm01","owasp:llm02","owasp:llm05"] },
  { probe: "glitch.Glitch", active: false, detector: "goodside.Glitch", owasp: ["owasp:llm05"] },
  { probe: "glitch.GlitchFull", active: false, detector: "goodside.Glitch", owasp: ["owasp:llm05"] },
  { probe: "goat.GOATAttack", active: false, detector: "judge.JailbreakOnlyAdversarial", owasp: ["owasp:llm01","owasp:llm09"] },
  { probe: "goodside.Davidjl", active: false, detector: "goodside.Glitch", owasp: ["owasp:llm05"] },
  { probe: "goodside.Tag", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "goodside.ThreatenJSON", active: true, detector: "goodside.PlainJSON", owasp: [] },
  { probe: "goodside.WhoIsRiley", active: true, detector: "goodside.RileyIsnt", owasp: ["owasp:llm09"] },
  { probe: "grandma.GrandmaIntent", active: false, detector: null, owasp: [] },
  { probe: "grandma.Slurs", active: true, detector: "unsafe_content.SlursReclaimedSlurs", owasp: [] },
  { probe: "grandma.Substances", active: true, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "grandma.Win10", active: true, detector: "productkey.Win5x5", owasp: ["owasp:llm06"] },
  { probe: "grandma.Win11", active: true, detector: "productkey.Win5x5", owasp: ["owasp:llm06"] },
  { probe: "latentinjection.LatentInjectionFactSnippetEiffel", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionFactSnippetEiffelFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionFactSnippetLegal", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionFactSnippetLegalFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionReport", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionReportFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionResume", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionResumeFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionTranslationEnFr", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionTranslationEnFrFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionTranslationEnZh", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentInjectionTranslationEnZhFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentJailbreak", active: true, detector: "unsafe_content.ToxicCommentModel", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentJailbreakFull", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentWhois", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentWhoisSnippet", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "latentinjection.LatentWhoisSnippetFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm01"] },
  { probe: "leakreplay.GuardianCloze", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.GuardianClozeFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.GuardianComplete", active: true, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.GuardianCompleteFull", active: false, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.LiteratureCloze", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.LiteratureClozeFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.LiteratureComplete", active: true, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.LiteratureCompleteFull", active: false, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.NYTCloze", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.NYTClozeFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.NYTComplete", active: true, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.NYTCompleteFull", active: false, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.PotterCloze", active: true, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.PotterClozeFull", active: false, detector: "base.TriggerListDetector", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.PotterComplete", active: true, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "leakreplay.PotterCompleteFull", active: false, detector: "leakreplay.StartsWith", owasp: ["owasp:llm06","owasp:llm10"] },
  { probe: "lmrc.Anthropomorphisation", active: false, detector: "lmrc.Anthro", owasp: [] },
  { probe: "lmrc.Bullying", active: true, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "lmrc.Deadnaming", active: true, detector: "base.TriggerListDetector", owasp: [] },
  { probe: "lmrc.Profanity", active: false, detector: "unsafe_content.SurgeProfanityAnimalReferences", owasp: [] },
  { probe: "lmrc.QuackMedicine", active: true, detector: "lmrc.QuackMedicine", owasp: [] },
  { probe: "lmrc.SexualContent", active: true, detector: "unsafe_content.SurgeProfanitySexual", owasp: [] },
  { probe: "lmrc.Sexualisation", active: true, detector: "unsafe_content.SurgeProfanitySexual", owasp: [] },
  { probe: "lmrc.SlurUsage", active: true, detector: "unsafe_content.SurgeProfanityRacialEthnic", owasp: [] },
  { probe: "malwaregen.Evasion", active: true, detector: "malwaregen.AnyCode", owasp: [] },
  { probe: "malwaregen.Payload", active: true, detector: "malwaregen.AnyCode", owasp: [] },
  { probe: "malwaregen.SubFunctions", active: true, detector: "malwaregen.AnyCode", owasp: [] },
  { probe: "malwaregen.TopLevel", active: true, detector: "malwaregen.AnyCode", owasp: [] },
  { probe: "misleading.FalseAssertion", active: true, detector: "misleading.MustRefuteClaimModel", owasp: ["owasp:llm09"] },
  { probe: "packagehallucination.Dart", active: true, detector: "packagehallucination.Dart", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.JavaScript", active: true, detector: "packagehallucination.JavaScriptNpm", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.Perl", active: true, detector: "packagehallucination.Perl", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.Python", active: true, detector: "packagehallucination.PythonPypi", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.RakuLand", active: true, detector: "packagehallucination.RakuLand", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.Ruby", active: true, detector: "packagehallucination.RubyGems", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "packagehallucination.Rust", active: true, detector: "packagehallucination.RustCrates", owasp: ["owasp:llm02","owasp:llm09"] },
  { probe: "phrasing.FutureTense", active: true, detector: "mitigation.Prefixes", owasp: ["owasp:llm01"] },
  { probe: "phrasing.FutureTenseFull", active: false, detector: "mitigation.Prefixes", owasp: ["owasp:llm01"] },
  { probe: "phrasing.PastTense", active: true, detector: "mitigation.Prefixes", owasp: ["owasp:llm01"] },
  { probe: "phrasing.PastTenseFull", active: false, detector: "mitigation.Prefixes", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackHateHumans", active: true, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackHateHumansFull", active: false, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackKillHumans", active: true, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackKillHumansFull", active: false, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackLongPrompt", active: true, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "promptinject.HijackLongPromptFull", active: false, detector: "promptinject.AttackRogueString", owasp: ["owasp:llm01"] },
  { probe: "propile.PIILeakQuadruplet", active: false, detector: "propile.PIILeak", owasp: ["owasp:llm06"] },
  { probe: "propile.PIILeakTriplet", active: false, detector: "propile.PIILeak", owasp: ["owasp:llm06"] },
  { probe: "propile.PIILeakTwin", active: false, detector: "propile.PIILeak", owasp: ["owasp:llm06"] },
  { probe: "propile.PIILeakUnstructured", active: false, detector: "propile.PIILeak", owasp: ["owasp:llm06"] },
  { probe: "realtoxicityprompts.RTPBlank", active: true, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPFlirtation", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPIdentity_Attack", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPInsult", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPProfanity", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPSevere_Toxicity", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPSexually_Explicit", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "realtoxicityprompts.RTPThreat", active: false, detector: "unsafe_content.ToxicCommentModel", owasp: [] },
  { probe: "sata.MLM", active: true, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "smuggling.FunctionMasking", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "smuggling.HomoglyphObfuscation", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm01"] },
  { probe: "smuggling.HypotheticalResponse", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "snowball.GraphConnectivity", active: true, detector: "snowball.DontStartYes", owasp: ["owasp:llm09"] },
  { probe: "snowball.GraphConnectivityFull", active: false, detector: "snowball.DontStartYes", owasp: ["owasp:llm09"] },
  { probe: "snowball.Primes", active: false, detector: "snowball.DontStartNo", owasp: ["owasp:llm09"] },
  { probe: "snowball.PrimesFull", active: false, detector: "snowball.DontStartNo", owasp: ["owasp:llm09"] },
  { probe: "snowball.Senators", active: false, detector: "snowball.DontStartYes", owasp: ["owasp:llm09"] },
  { probe: "snowball.SenatorsFull", active: false, detector: "snowball.DontStartYes", owasp: ["owasp:llm09"] },
  { probe: "suffix.BEAST", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "suffix.GCG", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "suffix.GCGCached", active: true, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "sysprompt_extraction.SystemPromptExtraction", active: true, detector: "sysprompt_extraction.PromptExtraction", owasp: ["owasp:llm01"] },
  { probe: "tap.PAIR", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "tap.TAP", active: false, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "tap.TAPCached", active: true, detector: "mitigation.MitigationBypass", owasp: [] },
  { probe: "test.Blank", active: false, detector: "any.AnyOutput", owasp: [] },
  { probe: "test.Test", active: false, detector: "always.Pass", owasp: [] },
  { probe: "topic.WordnetAllowedWords", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm10"] },
  { probe: "topic.WordnetBlockedWords", active: false, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm10"] },
  { probe: "topic.WordnetControversial", active: true, detector: "mitigation.MitigationBypass", owasp: ["owasp:llm10"] },
  { probe: "visual_jailbreak.FigStep", active: false, detector: "visual_jailbreak.FigStep", owasp: ["owasp:llm01"] },
  { probe: "visual_jailbreak.FigStepFull", active: false, detector: "visual_jailbreak.FigStep", owasp: ["owasp:llm01"] },
  { probe: "web_injection.ColabAIDataLeakage", active: true, detector: "web_injection.MarkdownExfilContent", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.MarkdownImageExfil", active: true, detector: "web_injection.MarkdownExfilBasic", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.MarkdownURIImageExfilExtended", active: true, detector: "web_injection.MarkdownExfilExtendedImage", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.MarkdownURINonImageExfilExtended", active: true, detector: "web_injection.MarkdownExfilExtendedNonImage", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.MarkdownXSS", active: true, detector: "web_injection.XSS", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.PlaygroundMarkdownExfil", active: true, detector: "web_injection.PlaygroundMarkdownExfil", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.StringAssemblyDataExfil", active: true, detector: "web_injection.MarkdownExfilBasic", owasp: ["owasp:llm02","owasp:llm06"] },
  { probe: "web_injection.TaskXSS", active: true, detector: "web_injection.XSS", owasp: ["owasp:llm02","owasp:llm06"] },
]);
