/** Explicit preview only; generated byte-for-byte from I1 SHIPPED_EXECUTION_PROFILES. Not a live API response. */
import type { ProfileView } from './isolationModel';
export const SHIPPED_PREVIEW_PROFILES:ProfileView[]=[
  {
    "body": {
      "schema": "regulait.execution-profile.v1",
      "name": "restricted",
      "workloadKinds": [
        "mcp_stdio",
        "code_exec",
        "engine_worker",
        "byoc_worker"
      ],
      "minClass": "user_space_kernel",
      "filesystem": {
        "rootReadOnly": true,
        "workDir": {
          "path": "/work",
          "tmpfsMiB": 256
        },
        "inputs": []
      },
      "network": {
        "mode": "gateway_only"
      },
      "process": {
        "uid": 10001,
        "capabilities": [],
        "noNewPrivileges": true,
        "seccomp": {
          "type": "RuntimeDefault"
        },
        "pids": {
          "workloadNproc": 128,
          "hostCgroupPidsMax": 512
        },
        "exec": "image_only"
      },
      "resources": {
        "cpuMillis": 1000,
        "memoryMiB": 1024,
        "wallClockSecondsPerCall": 300,
        "wallClockSecondsPerSession": 1800,
        "outputBytes": 16777216
      },
      "secrets": "none",
      "persistence": "none",
      "runsc": {
        "ociSeccomp": true,
        "sidecarUsagePolicy": "STRICT",
        "sidecarReleaseEnforcementPolicy": "ALWAYS",
        "platform": "systrap",
        "directfs": false
      },
      "attestation": {
        "probes": [
          "runtime_identity",
          "proc_status",
          "seccomp_enforced",
          "root_read_only",
          "egress_literal_address",
          "egress_dns",
          "network_interfaces",
          "no_executor_credentials",
          "visible_limits",
          "host_cgroup_limits",
          "runtime_config"
        ],
        "executorMaxAgeMinutes": 120,
        "perPlacement": true
      }
    },
    "digest": "9b8e0c493874ba6768bb00ec331827a76f44f64cc5024f10adc9380f20a21496",
    "version": 1,
    "retired": false
  },
  {
    "body": {
      "schema": "regulait.execution-profile.v1",
      "name": "restricted-microvm",
      "workloadKinds": [
        "mcp_stdio",
        "code_exec",
        "engine_worker",
        "byoc_worker"
      ],
      "minClass": "microvm",
      "filesystem": {
        "rootReadOnly": true,
        "workDir": {
          "path": "/work",
          "tmpfsMiB": 256
        },
        "inputs": []
      },
      "network": {
        "mode": "gateway_only"
      },
      "process": {
        "uid": 10001,
        "capabilities": [],
        "noNewPrivileges": true,
        "seccomp": {
          "type": "RuntimeDefault"
        },
        "pids": {
          "workloadNproc": 128,
          "hostCgroupPidsMax": 512
        },
        "exec": "image_only"
      },
      "resources": {
        "cpuMillis": 1000,
        "memoryMiB": 1024,
        "wallClockSecondsPerCall": 300,
        "wallClockSecondsPerSession": 1800,
        "outputBytes": 16777216
      },
      "secrets": "none",
      "persistence": "none",
      "runsc": {
        "ociSeccomp": true,
        "sidecarUsagePolicy": "STRICT",
        "sidecarReleaseEnforcementPolicy": "ALWAYS",
        "platform": "systrap",
        "directfs": false
      },
      "attestation": {
        "probes": [
          "runtime_identity",
          "proc_status",
          "seccomp_enforced",
          "root_read_only",
          "egress_literal_address",
          "egress_dns",
          "network_interfaces",
          "no_executor_credentials",
          "visible_limits",
          "host_cgroup_limits",
          "runtime_config"
        ],
        "executorMaxAgeMinutes": 120,
        "perPlacement": true
      }
    },
    "digest": "9a2363321acbd41914826143273037829107c99a61db21adb03deebfdb39aacd",
    "version": 1,
    "retired": false
  },
  {
    "body": {
      "schema": "regulait.execution-profile.v1",
      "name": "engine-worker",
      "workloadKinds": [
        "engine_worker"
      ],
      "minClass": "user_space_kernel",
      "filesystem": {
        "rootReadOnly": true,
        "workDir": {
          "path": "/work",
          "tmpfsMiB": 1024
        },
        "inputs": [
          {
            "name": "jobs",
            "mountPath": "/jobs"
          }
        ]
      },
      "network": {
        "mode": "gateway_only"
      },
      "process": {
        "uid": 10001,
        "capabilities": [],
        "noNewPrivileges": true,
        "seccomp": {
          "type": "RuntimeDefault"
        },
        "pids": {
          "workloadNproc": 256,
          "hostCgroupPidsMax": 768
        },
        "exec": "image_only"
      },
      "resources": {
        "cpuMillis": 2000,
        "memoryMiB": 2048,
        "wallClockSecondsPerCall": 1800,
        "wallClockSecondsPerSession": 1800,
        "outputBytes": 67108864
      },
      "secrets": "task_scoped",
      "persistence": "none",
      "runsc": {
        "ociSeccomp": true,
        "sidecarUsagePolicy": "STRICT",
        "sidecarReleaseEnforcementPolicy": "ALWAYS",
        "platform": "systrap",
        "directfs": false
      },
      "attestation": {
        "probes": [
          "runtime_identity",
          "proc_status",
          "seccomp_enforced",
          "root_read_only",
          "egress_literal_address",
          "egress_dns",
          "network_interfaces",
          "no_executor_credentials",
          "visible_limits",
          "host_cgroup_limits",
          "runtime_config"
        ],
        "executorMaxAgeMinutes": 120,
        "perPlacement": true
      }
    },
    "digest": "1a9700e7e04883b04b5ffcce625d4f2a9fda6ba17b1a9a474a638c9f8d4dc7c3",
    "version": 1,
    "retired": false
  }
];
