import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const path="/ui/e2e/fixtures/bom-preview.html";
const json=(route:any,body:unknown,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});
async function setup(page:Page,mode="normal"){
 await page.route("**/auth/me",route=>json(route,{userId:id(5),isAdmin:true,via:"session",user:{id:id(5),email:"synthetic@example.invalid",displayName:"Synthetic reviewer"},mustChangePassword:false,totpEnabled:true,passwordSet:true,mfaSetupRequired:false}));
 await page.route("**/v1/me",route=>json(route,{userId:id(5),isAdmin:true,user:{id:id(5),email:"synthetic@example.invalid",displayName:"Synthetic reviewer"}}));
 await page.goto(`${path}?mode=${mode}`);await expect(page.getByRole("heading",{name:"Synthetic BOM UI preview"})).toBeVisible();
}
async function inspect(page:Page){await page.getByRole("button",{name:"Inspect snapshot version 1"}).click();}
const snapshotCard=(page:Page)=>page.locator("section").filter({has:page.getByText("Snapshot version 1",{exact:true})}).first();
test("snapshot/drift/export preserve digest-only display and bundle format",async({page})=>{
 await setup(page);await inspect(page);await expect(snapshotCard(page).getByText("Not recorded",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Check inventory drift"}).click();await expect(page.getByText("Not evidence",{exact:true})).toBeVisible();await expect(page.getByText(`Agent ${id(1)}: changed hash`)).toBeVisible();
 await expect(page.locator("body")).not.toContainText("SYNTHETIC_PRIVATE_VERSION");
 await snapshotCard(page).getByLabel("BOM bundle format").selectOption("spdx-3.0.1");
 const download=page.waitForEvent("download");await snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true}).click();expect((await download).suggestedFilename()).toBe(`ai-bom-${id(9)}-spdx-3.0.1.tar.gz`);
 await expect(page.getByRole("region",{name:"Synthetic operation log"})).toContainText("snapshot bundle spdx-3.0.1");
});
test("decision view records gaps and downloads a bundle without raw content",async({page})=>{
 await setup(page);const card=page.locator("section").filter({has:page.getByText("Decision BOM",{exact:true})}).first();await expect(card).toContainText("Historical decision evidence");
 const download=page.waitForEvent("download");await card.getByRole("button",{name:"Download Decision BOM bundle"}).click();expect((await download).suggestedFilename()).toBe(`decision-bom-${id(7)}.tar.gz`);
 await expect(card).toContainText("Predates workload identity");await expect(card).toContainText("does not establish completeness");
});
test("production B3 adapter reads exact metadata and has unavailable B4 controls",async({page})=>{
 let lists=0,drifts=0,writes=0;
 await page.route(`**/v1/ai-bom/agent/${id(1)}/snapshots`,route=>{if(route.request().method()==="POST"){writes++;return json(route,{},501)}lists++;return json(route,{subject:{kind:"agent",id:id(1)},released:false,snapshots:[{id:id(9),version:1,serialNumber:`urn:uuid:${id(9)}`,trigger:"on_demand",bodySha256:"a".repeat(64),keyId:"synthetic-key",createdAt:"2026-10-10T12:00:00.000Z",formats:["cyclonedx-1.7"]}]})});
 await page.route(`**/v1/ai-bom/agent/${id(1)}/drift`,route=>{drifts++;return json(route,{subject:{kind:"agent",id:id(1)},evidence:false,baseline:{snapshotId:id(9),version:1,serialNumber:`urn:uuid:${id(9)}`,createdAt:"2026-10-10T12:00:00.000Z"},changes:[]})});
 await setup(page,"api");await expect(page.getByRole("button",{name:"Take signed snapshot"})).toBeDisabled();await inspect(page);await expect(page.getByText("Snapshot inspection and verifiable bundle downloads are unavailable on this gateway.")).toBeVisible();await page.getByRole("button",{name:"Check inventory drift"}).click();await expect(page.getByText(/No inventory changes measured/)).toBeVisible();expect(lists).toBe(1);expect(drifts).toBe(1);expect(writes).toBe(0);
});
test("unknown assurance vocabulary remains safe and unmeasured",async({page})=>{await setup(page,"unknown");await inspect(page);await expect(snapshotCard(page)).toContainText("Unrecognised section");await expect(snapshotCard(page)).toContainText("Additional assurance is not established");await expect(page.locator("body")).not.toContainText("[object Object]");});
test("pending, missing, mismatched, denied and failed inspection never enable snapshot export",async({page})=>{
 for(const mode of ["pending","missing","mismatch","deny","inspection-error"]){await setup(page,mode);await inspect(page);await expect(snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true})).toBeDisabled();if(mode==="mismatch"||mode==="inspection-error")await expect(snapshotCard(page)).toContainText("Snapshot assurance is unavailable");}
});
test("finite and lapsed locks remain distinct from anchored assurance",async({page})=>{for(const [mode,label] of [["finite","Anchored with a time-limited lock"],["lapsed","Anchor lock has lapsed"]]){await setup(page,mode);await inspect(page);await expect(snapshotCard(page).getByText(label!,{exact:true})).toBeVisible();}});
test("bundle upload never renders raw text and distinguishes unverifiable sections",async({page})=>{
 await setup(page);const verify=page.locator("section").filter({has:page.getByText("Verify a BOM bundle",{exact:true})}).first();
 await verify.getByLabel("BOM bundle to verify",{exact:true}).setInputFiles({name:"synthetic.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({synthetic:true,raw:"SYNTHETIC_RAW_SECRET",keys:["SYNTHETIC_PRIVATE_KEY"]}))});await verify.getByRole("button",{name:"Verify loaded BOM bundle"}).click();await expect(verify).toContainText("Trust root: this deployment's recorded keys");await expect(verify.getByText("Unverifiable",{exact:true})).toBeVisible();await expect(page.locator("body")).not.toContainText("SYNTHETIC_RAW_SECRET");
 await verify.getByLabel("BOM bundle to verify",{exact:true}).setInputFiles({name:"bad.json",mimeType:"application/json",buffer:Buffer.from("SYNTHETIC_PRIVATE_KEY invalid")});await verify.getByRole("button",{name:"Verify loaded BOM bundle"}).click();await expect(verify).toContainText("No verification result was established");await expect(verify).not.toContainText("Trust root: this deployment's recorded keys");
});
test("confirmation is cancelled when subject changes and keyboard focus returns",async({page})=>{
 await setup(page);const trigger=page.getByRole("button",{name:"Take signed snapshot"});await trigger.focus();await page.keyboard.press("Enter");await expect(page.getByRole("dialog",{name:"Take signed AI BOM snapshot"})).toBeVisible();await page.keyboard.press("Escape");await expect(trigger).toBeFocused();await trigger.click();await page.evaluate(()=>{(window as unknown as {switchBomSubject:()=>void}).switchBomSubject()});await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("region",{name:"Synthetic operation log"})).not.toContainText("created");
});
test("empty/error/unavailable states remain honest and axe passes both themes",async({page},testInfo)=>{
 await setup(page,"empty");await expect(page.getByText("No signed snapshots",{exact:true})).toBeVisible();await setup(page,"error");await expect(page.getByText("Snapshot metadata is unavailable.",{exact:false})).toBeVisible();await expect(page.locator("body")).not.toContainText("SYNTHETIC_SECRET_ERROR");
 await setup(page);await inspect(page);
 for(const theme of ["light","dark"]){await page.evaluate(t=>{document.documentElement.dataset.theme=t},theme);await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));const axe=await new AxeBuilder({page}).analyze();expect(axe.violations).toEqual([]);await page.screenshot({path:testInfo.outputPath(`bom-${theme}.png`),fullPage:true});}
});

test("agent and model-card BOM tabs work by keyboard without replacing editor state",async({page})=>{
 const {installBuilderMock}=await import("./builder-fixtures");await installBuilderMock(page);
 const registry=[{id:id(1),name:"Synthetic agent",provider:"mock",model:"synthetic-model",tier:0,enabled:true,lifecycleStatus:"active",costPerMTokIn:null,costPerMTokOut:null},{id:id(2),name:"Second synthetic agent",provider:"mock",model:"synthetic-model-2",tier:0,enabled:true,lifecycleStatus:"active",costPerMTokIn:null,costPerMTokOut:null}];
 await page.route("**/v1/agents",route=>json(route,{agents:registry}));
 const bomReads:string[]=[];await page.route("**/v1/ai-bom/agent/*/snapshots",route=>{const subjectId=new URL(route.request().url()).pathname.split("/")[4]!;bomReads.push(subjectId);return json(route,{subject:{kind:"agent",id:subjectId},released:false,snapshots:[]})});
 await page.goto("/ui/admin/agents");await page.getByLabel("Agent for AI BOM evidence").selectOption(id(1));expect(bomReads).toEqual([]);const overview=page.getByRole("tab",{name:"Overview",exact:true});await overview.focus();await page.keyboard.press("ArrowRight");await expect(page.getByRole("tab",{name:"AI BOM",exact:true})).toHaveAttribute("aria-selected","true");await expect(page.getByText("No signed snapshots",{exact:true})).toBeVisible();await page.getByLabel("Agent for AI BOM evidence").selectOption(id(2));await expect.poll(()=>bomReads).toEqual([id(1),id(2)]);await page.getByRole("tab",{name:"AI BOM",exact:true}).focus();await page.keyboard.press("Home");await expect(overview).toHaveAttribute("aria-selected","true");
 const card={id:id(6),agentId:id(1),customProviderId:null,intendedUse:"Synthetic summaries",limitations:null,dataClaims:{},biasFairness:[],standardRefs:[],state:"unsigned",daysUntilExpiry:null,subjectName:"Synthetic agent",approvals:[],evidence:[],completeness:{complete:false,missing:["evidence"],bias:{declared:0,assessed:0,waived:0,unevidenced:0,complete:false,disclaimer:"Unmeasured"}},createdAt:"2026-10-10T12:00:00.000Z",autofill:null,staleness:null};
 await page.route("**/v1/mrm/status",route=>json(route,{enforced:true,warnDays:30,stalenessRecertEnabled:true,stalenessRecertThreshold:1,posture:"declared",label:"Synthetic fixture",cards:1,approved:0,expiring:0,expired:0,pending:0,unsigned:1,revoked:0,note:"Mock"}));
 await page.route("**/v1/mrm/expiring",route=>json(route,{warnDays:30,items:[]}));await page.route("**/v1/mrm/cards",route=>json(route,{cards:[card],enforced:true}));await page.route(`**/v1/mrm/cards/${id(6)}`,route=>json(route,{card}));
 await page.goto("/ui/admin/model-risk");await page.getByRole("button",{name:"Open",exact:true}).click();const editor=page.getByPlaceholder("eval run id from /admin/evals");await editor.fill("synthetic-unsaved-evidence");const evidenceTab=page.getByRole("tab",{name:"Model card and evidence"});await evidenceTab.focus();await page.keyboard.press("End");await expect(page.getByRole("tab",{name:"AI BOM",exact:true})).toHaveAttribute("aria-selected","true");await expect(page.getByRole("tabpanel",{name:"Model card AI BOM"})).toContainText("No signed snapshots");await page.keyboard.press("Home");await expect(evidenceTab).toHaveAttribute("aria-selected","true");await expect(page.getByRole("tabpanel",{name:"Model card and evidence"})).toBeVisible();await expect(editor).toHaveValue("synthetic-unsaved-evidence");
});

test("BOM posture requires step-up and locks after successful write with failed refresh",async({page})=>{
 const {installBuilderMock}=await import("./builder-fixtures");const {confirmStepUp,requireStepUpOn}=await import("./step-up-harness");await installBuilderMock(page);
 const stored:Record<string,unknown>={decisionFactsCapture:"on",decisionBomFinality:"anchored",bomExportRoles:"admins_only",bomPersonIdentifiers:"id_only",aiBomSnapshotTriggers:"sign_off_events",aiBomSnapshotWithoutKey:"refuse",cyclonedxExportVersions:["1.6","1.7"],bomExportRateLimitPerMinute:30,decisionBomFiniteLockFinality:"refuse"};
 let failed=false,writes=0;await page.route("**/v1/org/settings",route=>{if(route.request().method()==="PUT"){writes++;Object.assign(stored,route.request().postDataJSON());failed=true;return json(route,{settings:stored});}return failed?json(route,{error:"synthetic_read_failed"},500):json(route,{settings:stored})});
 await page.route("**/v1/org/posture",route=>json(route,{hardened:true,summary:{enforcementSatisfied:0,enforcementTotal:0,optimisationSatisfied:0,optimisationTotal:0,blockedByEnvironment:[]},controls:[],execution:{mode:"normal",reason:null}}));
 const stepUp=await requireStepUpOn(page,{method:"PUT",path:"/v1/org/settings",kind:"settings_relax"});await page.goto("/ui/admin/enforcement-posture");
 await expect(page.getByLabel("CycloneDX export versions",{exact:true})).toHaveValue("1.7,1.6");const facts=page.locator("form").filter({has:page.getByLabel("Decision BOM facts",{exact:true})});await facts.getByLabel("Decision BOM facts",{exact:true}).selectOption("off");await facts.getByRole("button",{name:"Review change"}).click();const dialog=page.getByRole("dialog",{name:"Change decision bom facts?"});await expect(dialog).toContainText("Stored value: on → New value: off");await dialog.getByRole("button",{name:"Save setting"}).click();await confirmStepUp(page);await stepUp.expectResentOnce();await expect(page.getByText(/This form stays locked/)).toBeVisible();expect(writes).toBe(1);await expect(page.getByRole("button",{name:"Review change"})).toHaveCount(0);failed=false;await page.getByRole("button",{name:"Retry loading current values"}).click();await expect(page.getByLabel("Decision BOM facts",{exact:true})).toHaveValue("off");await expect(page.getByText("Decision BOM: not captured",{exact:true})).toBeVisible();
});

const b4Common=["bundle_manifest_signature","bundle_manifest_files","bundle_subject","bundle_email_scan","body_version","body_schema","body_signature"];
const b4Capabilities={access:"admin",exportRoles:"admins_only",auditorGrant:null,canExport:true,exportUnavailableReason:null as null|"export_signing_key_absent",canVerify:true,canViewDrift:true,exportRequiresStepUp:false,rateLimitPerMinute:30};
function b4Verification(){return {trust:"deployment_registry",source:"ai_bom_snapshot",bodyVersion:"regulait.ai-bom.v1",identity:{subject:"ai-bom",snapshotId:id(9),subjectKind:"agent",subjectId:id(1),version:1,serialNumber:`urn:uuid:${id(9)}`},outcome:"valid_with_unverifiable",checks:[...b4Common,"rendering_hashes","serial_number","supersedes"].map((check,i)=>({check,status:i<4?"unverifiable":"valid",reason:i<4?"not_a_bundle":null,ref:null})),sections:[],cannotProve:["facts_true","signing_time_beyond_anchor"],manifest:null,verifiedAt:"2026-10-10T12:00:00.000Z",capabilities:b4Capabilities};}
async function b4Metadata(page:Page){
 await page.route(`**/v1/ai-bom/agent/${id(2)}/snapshots`,route=>json(route,{subject:{kind:"agent",id:id(2)},released:false,snapshots:[]}));
 await page.route(`**/v1/ai-bom/agent/${id(1)}/snapshots`,route=>json(route,{subject:{kind:"agent",id:id(1)},released:false,snapshots:[{id:id(9),version:1,serialNumber:`urn:uuid:${id(9)}`,trigger:"on_demand",bodySha256:"a".repeat(64),keyId:"synthetic-key",createdAt:"2026-10-10T12:00:00.000Z",formats:["cyclonedx-1.7"]}]}));
 await page.route(`**/v1/decisions/${id(7)}/bom`,route=>json(route,{error:"not_built"},501));
}
test("production B4 stored verification and gzip download use exact frozen HTTP contracts",async({page})=>{
 const {createHash}=await import("node:crypto");const {gzipSync}=await import("node:zlib");const bytes=gzipSync(Buffer.from("synthetic transport fixture; no actual signature"));const requests:unknown[]=[];await b4Metadata(page);
 await page.route("**/v1/boms/verify",route=>{expect(route.request().headers()["x-regulait-csrf"]).toBe("1");requests.push(route.request().postDataJSON());return json(route,b4Verification())});
 await page.route(`**/v1/ai-bom/snapshots/${id(9)}?format=native`,route=>route.fulfill({status:200,headers:{"content-type":"application/gzip","content-disposition":'attachment; filename="regulait-synthetic.tar.gz"',"x-regulait-bundle-schema":"regulait.export-bundle/3","x-regulait-bundle-subject":"ai-bom","x-regulait-bundle-sha256":createHash("sha256").update(bytes).digest("hex"),"x-regulait-bundle-manifest-sha256":"a".repeat(64),"x-regulait-export-signing-key-id":"synthetic","x-regulait-export-signing-key-fingerprint":"sha256:"+"a".repeat(64),"x-regulait-bom-body-sha256":"a".repeat(64)},body:bytes}));
 await setup(page,"b4");await inspect(page);await expect(snapshotCard(page)).toContainText("Native body signature");await expect(snapshotCard(page)).toContainText("Unverifiable");expect(requests).toEqual([{source:"ai_bom_snapshot",snapshotId:id(9)}]);const download=page.waitForEvent("download");await snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true}).click();expect((await download).suggestedFilename()).toBe(`ai-bom-${id(9)}-native.tar.gz`);await expect(page.getByText("Decision evidence is unavailable or pending.",{exact:false})).toBeVisible();
});
test("production B4 refuses incomplete checks, wrong identities, denied capability and current 501",async({page})=>{
 await b4Metadata(page);let state="missing";
 await page.route("**/v1/boms/verify",route=>{const body=b4Verification();if(state==="501")return json(route,{error:"not_built",detail:"SYNTHETIC_PRIVATE_DETAIL"},501);if(state==="missing")body.checks=body.checks.filter(c=>c.check!=="body_signature");if(state==="wrong")body.identity.snapshotId=id(8);if(state==="denied")body.capabilities={...b4Capabilities,canExport:false,exportUnavailableReason:"export_signing_key_absent"};return json(route,body)});
 for(state of ["missing","wrong","denied","501"]){await setup(page,"b4");await inspect(page);await expect(snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true})).toBeDisabled();if(state!=="denied")await expect(snapshotCard(page)).toContainText("Snapshot assurance is unavailable");await expect(page.locator("body")).not.toContainText("SYNTHETIC_PRIVATE_DETAIL");}
});
test("production B4 rejects archive body-binding mismatch without downloading",async({page})=>{
 await b4Metadata(page);await page.route("**/v1/boms/verify",route=>json(route,b4Verification()));await page.route(`**/v1/ai-bom/snapshots/${id(9)}?format=native`,route=>route.fulfill({status:200,contentType:"application/gzip",headers:{"x-regulait-bom-body-sha256":"b".repeat(64)},body:Buffer.from([31,139,8,0])}));let downloads=0;page.on("download",()=>downloads++);await setup(page,"b4");await inspect(page);await snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true}).click();await expect(page.getByText("The BOM operation was refused or is unavailable. No new evidence was established.")).toBeVisible();expect(downloads).toBe(0);
});
test("production B4 hides forbidden export/verify actions and clears prior subject results",async({page})=>{
 await b4Metadata(page);let denyUpload=false;
 await page.route("**/v1/boms/verify",route=>{const request=route.request().postDataJSON();if(request.source!=="bundle")return json(route,b4Verification());if(denyUpload)return json(route,{error:"bom_export_forbidden",detail:"SYNTHETIC_PRIVATE_DETAIL"},403);return json(route,{...b4Verification(),source:"bundle",identity:null,bodyVersion:null,outcome:"invalid",checks:[{check:"body_schema",status:"invalid",reason:"bundle_unreadable",ref:null}],cannotProve:[]});});
 await page.route(`**/v1/ai-bom/snapshots/${id(9)}?format=native`,route=>json(route,{error:"bom_export_forbidden",detail:"SYNTHETIC_PRIVATE_DETAIL"},403));
 await setup(page,"b4");await inspect(page);await snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true}).click();await expect(snapshotCard(page).getByRole("button",{name:"Download BOM bundle",exact:true})).toHaveCount(0);
 const verify=page.locator("section").filter({has:page.getByText("Verify a BOM bundle",{exact:true})}).first();await verify.getByLabel("BOM bundle to verify",{exact:true}).setInputFiles({name:"synthetic.tar.gz",mimeType:"application/gzip",buffer:Buffer.from([31,139,8,0])});await verify.getByRole("button",{name:"Verify loaded BOM bundle"}).click();await expect(verify.getByText("Invalid",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Switch subject",exact:true}).click();await expect(verify.getByText("Invalid",{exact:true})).toHaveCount(0);
 denyUpload=true;await verify.getByLabel("BOM bundle to verify",{exact:true}).setInputFiles({name:"synthetic.tar.gz",mimeType:"application/gzip",buffer:Buffer.from([31,139,8,0])});await verify.getByRole("button",{name:"Verify loaded BOM bundle"}).click();await expect(verify.getByRole("button",{name:"Verify loaded BOM bundle"})).toHaveCount(0);await expect(verify.getByLabel("BOM bundle to verify",{exact:true})).toBeDisabled();await expect(page.locator("body")).not.toContainText("SYNTHETIC_PRIVATE_DETAIL");
});
test("a completed capture for a previous subject never announces evidence for the new subject",async({page})=>{
 await setup(page,"capture-race");await page.getByRole("button",{name:"Take signed snapshot"}).click();await page.getByRole("dialog").getByRole("button",{name:"Take snapshot",exact:true}).click();await page.evaluate(()=>{const w=window as unknown as {switchBomSubject:()=>void;finishBomCapture:()=>void};w.switchBomSubject();});await expect(page.getByRole("dialog")).toHaveCount(0);await page.evaluate(()=>{(window as unknown as {finishBomCapture:()=>void}).finishBomCapture();});await expect(page.getByRole("region",{name:"Synthetic operation log"})).toContainText(`created ${id(1)}`);await expect(page.getByText("Signed snapshot recorded.",{exact:true})).toHaveCount(0);
});
test("production Decision BOM binds recorded versions through read, verification and export HTTP calls",async({page})=>{
 const {createHash}=await import("node:crypto");const at="2026-10-10T12:00:00.000Z",sections=["decision","receipt","principal","actors","action","policy","model","approval","outcome","cost","trace","proof"],seen:unknown[]=[];
 const canonical=(v:any):string=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?"["+v.map(canonical).join(",")+"]":"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}";
 function read(version:number){const receipt='{"receiptSeq":5,"v":"v2"}',completeness=Object.fromEntries(sections.map(s=>[s,["decision","receipt","principal","proof"].includes(s)?{status:"recorded"}:{status:"not_recorded",reason:"no_bound_row"}]));const document={v:"regulait.decision-bom.v1",id:id(20+version),auditId:id(7),version,supersedes:version===1?null:id(20),finality:"chain_signed",decision:{auditSeq:41,at,objectType:"mcp_tool",objectId:null,serverId:null,toolName:null,effect:"allow",ruleId:null,ruleChain:[]},receipt:{receiptSeq:5,payloadHash:createHash("sha256").update(receipt).digest("hex"),keyId:"synthetic",payload:receipt,signature:"A".repeat(86)},principal:{sponsorUserId:id(5)},actors:null,action:null,policy:null,model:null,approval:null,outcome:null,cost:null,trace:null,proof:{chain:[{seq:41,contentHash:"a".repeat(64),prevHash:"0".repeat(64),rowHash:"b".repeat(64)}],anchor:null},facts:{payload:null,addenda:[]},completeness,basis:{auditSeq:41,anchorId:null,receiptSeq:5,aiBomSnapshotId:null}};const body=canonical(document),bodySha256=createHash("sha256").update(body).digest("hex"),summary={id:document.id,version,supersedes:document.supersedes,finality:document.finality,bodySha256,keyId:"synthetic",createdAt:at};return {auditId:id(7),bom:{...summary,body,signature:"A".repeat(86),aiBomSnapshotId:null,reportedFinality:"chain_signed"},document,versions:[{...summary,id:id(21),version:1,supersedes:null}, {...summary,id:id(22),version:2,supersedes:id(20)}],renderings:[],bundle:{schema:"regulait.export-bundle/3",subject:"decision-bom",href:`/v1/decisions/${id(7)}/bom/bundle?version=${version}`},capabilities:b4Capabilities};}
 // Synthetic DTO/wire test only: signature and chain bytes are not cryptographic fixtures.
 await page.route(`**/v1/ai-bom/agent/${id(1)}/snapshots`,route=>json(route,{subject:{kind:"agent",id:id(1)},released:false,snapshots:[]}));
 await page.route(`**/v1/decisions/${id(7)}/bom**`,route=>{const url=new URL(route.request().url());if(url.pathname.endsWith("/bundle")){seen.push(url.search);return json(route,{error:"bom_export_forbidden"},403);}const version=Number(url.searchParams.get("version")||2);seen.push(`read:${version}`);return json(route,read(version));});
 await page.route("**/v1/boms/verify",route=>{const req=route.request().postDataJSON();seen.push(req);const r=read(req.version),specific=["receipt_signature","receipt_payload_hash","receipt_facts_binding","facts_addenda_chain","facts_addenda_signatures","sections_projection","chain_links","decision_content_binding","anchor_record","anchor_imprint","tsa_token","finality","ai_bom_link"];return json(route,{...b4Verification(),source:"decision_bom",bodyVersion:"regulait.decision-bom.v1",identity:{subject:"decision-bom",auditId:id(7),bomId:r.bom.id,version:req.version,recordedFinality:"chain_signed",reportedFinality:"chain_signed",receiptPayloadVersion:"v2"},checks:[...b4Common,...specific].map((check,i)=>({check,status:i<4||check==="decision_content_binding"?"unverifiable":"valid",reason:i<4?"not_a_bundle":check==="decision_content_binding"?"preimage_not_exported":null,ref:null})),sections:sections.map(section=>{const c=r.document.completeness[section]!;return {section,status:"valid",completeness:c.status,notRecordedReason:c.reason??null};}),cannotProve:["nothing_omitted_after_anchor","facts_true","signing_time_beyond_anchor","destination_tamper_resistant","decision_row_content"]});});
 await setup(page,"b4");const card=page.locator("section").filter({has:page.getByText("Decision BOM",{exact:true})}).first();await expect(card.getByLabel("Decision BOM version")).toHaveValue("2");await card.getByLabel("Decision BOM version").selectOption("1");await expect(card.getByLabel("Decision BOM version")).toHaveValue("1");await card.getByRole("button",{name:"Download Decision BOM bundle"}).click();await expect(card.getByRole("button",{name:"Download Decision BOM bundle"})).toHaveCount(0);expect(seen).toContainEqual({source:"decision_bom",auditId:id(7),version:1});expect(seen).toContain("?version=1");
});
