/**
 * ADR-0189 slice B5: OFFLINE validation of AI BOM SPDX 3.0.1 renderings against
 * the OFFICIAL SPDX 3.0.1 JSON schema (draft 2020-12, generated by shacl2code),
 * vendored byte for byte in `packages/shared/vendor/spdx-3.0.1/` (amendment 7;
 * source and sha256 in THIRD_PARTY.md). Compiled with the pinned `ajv` 8.20.0
 * (`Ajv2020`) and `ajv-formats` 3.0.1, as spike B0 `validators.mjs` did:
 *
 *  - the schema is read from that local file and its SHA-256 must equal
 *    `SPDX_SCHEMA_SHA256` before it is compiled; a changed file refuses to
 *    compile (fail closed). `loadSchema` refuses any remote reference, so no
 *    runtime download can happen (air-gapped, ADR-0176);
 *  - `strict: true`, `strictRequired: false` (the generated schema uses
 *    `required` inside its top-level `if`), `allErrors: true`;
 *  - compiled ONCE per process, lazily.
 *
 * The JSON schema is necessary but NOT sufficient (R12 §5: a `suppliedBy`
 * pointing at a `Tool` passes it and fails SHACL). CI therefore also runs the
 * official SHACL model over renderings made by this code (`scripts/spdx3/`),
 * and the builder runs its own mandatory-property check (R3,
 * `spdxMandatoryMissing`).
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import type { ValidateFunction } from "ajv";
import addFormatsImport from "ajv-formats";

const require = createRequire(import.meta.url);
// ajv-formats is CommonJS with a default export; under NodeNext the namespace may arrive wrapped
const addFormats = ((addFormatsImport as unknown as { default?: unknown }).default ?? addFormatsImport) as (ajv: Ajv2020, opts: { mode: "full" }) => Ajv2020;
const versionOf = (pkg: string) => (JSON.parse(readFileSync(require.resolve(`${pkg}/package.json`), "utf8")) as { version: string }).version;

/** the vendored official schema; `src/bom` and `dist/bom` both sit two levels below the package root */
export const SPDX_SCHEMA_FILE = fileURLToPath(new URL("../../vendor/spdx-3.0.1/spdx-json-schema.json", import.meta.url));
/** https://spdx.org/schema/3.0.1/spdx-json-schema.json as fetched 2026-10-10 (spike B0, R12; THIRD_PARTY.md) */
export const SPDX_SCHEMA_SHA256 = "582c64e809d5b3ef9bd0c4de13a32391b47b0284a3e8d199569fb96f649234b1";

/** the validator identity stored with each rendering (`bom_renderings.validator`) */
export function spdxValidatorId(): string {
  return `ajv ${versionOf("ajv")} ajv-formats ${versionOf("ajv-formats")} spdx-json-schema-3.0.1 sha256:${SPDX_SCHEMA_SHA256}`;
}

/** read the vendored schema and refuse it unless its bytes are the pinned ones */
export function readPinnedSpdxSchema(file = SPDX_SCHEMA_FILE, expected = SPDX_SCHEMA_SHA256): Record<string, unknown> {
  const bytes = readFileSync(file);
  const actual = createHash("sha256").update(bytes).digest("hex");
  if (actual !== expected) throw new Error(`SPDX 3.0.1 schema ${file}: sha256 ${actual} is not the pinned ${expected} (refused)`);
  return JSON.parse(bytes.toString("utf8")) as Record<string, unknown>;
}

export function buildSpdxAjv(): Ajv2020 {
  const ajv = new Ajv2020({
    strict: true,
    strictRequired: false,
    allErrors: true,
    useDefaults: false,
    validateFormats: true,
    loadSchema: (uri: string) => {
      throw new Error(`remote schema refused: ${uri}`);
    },
  });
  addFormats(ajv, { mode: "full" });
  return ajv;
}

let compiled: ValidateFunction | null = null;
function validator(): ValidateFunction {
  if (!compiled) compiled = buildSpdxAjv().compile(readPinnedSpdxSchema());
  return compiled;
}

export interface SpdxValidation {
  valid: boolean;
  errors: Array<{ path: string; message: string }>;
}

export function validateSpdx(doc: unknown): SpdxValidation {
  const fn = validator();
  if (fn(doc)) return { valid: true, errors: [] };
  return { valid: false, errors: (fn.errors ?? []).map((e) => ({ path: e.instancePath, message: e.message ?? e.keyword })) };
}

/** compile now (boot or a test's beforeAll), so the first snapshot does not pay for it */
export function warmSpdxValidator(): void {
  validator();
}
