-- ADR-0182 (ADR-0175 batch D4) S5 — PF-14: the alert SLA sweep's
-- "escalated once" marker, read cheaply.
--
-- `runAlertSlaSweep` (apps/gateway/src/alert-ownership.ts) escalates an
-- unowned governance-alert episode to the admins ONCE; the marker is the
-- escalation's own audit row (`rule_id = 'governance-alert-escalated'`,
-- `object_id` = the episode). The audit trail has no index on `object_id`, so
-- without this every 15-minute pass would scan all of `audit_log` once per
-- unowned episode. This partial index holds only the escalation rows (a
-- handful per episode, pruned with everything else), as 0154 does for the
-- prune markers. No table, column or default changes: nothing to grandfather.
CREATE INDEX IF NOT EXISTS "audit_log_alert_escalated_idx" ON "audit_log" ("object_id") WHERE "rule_id" = 'governance-alert-escalated';
