/**
 * ADR-0190 I3 — THE EXECUTOR'S OWN KEY (ADR-0188 decision 5: a workload
 * authenticates with a key it holds; the gateway holds only the public half as
 * a `jwk` credential of the executor's `worker_runtime` identity).
 *
 * Ed25519 (EdDSA), generated by the executor itself; the private key never
 * leaves its own volume. Persisted as PKCS#8 PEM, mode 0600, written
 * atomically and durably (`write-file-atomic`, then the directory fsynced) so
 * a crash never leaves a truncated or world-readable file. The public JWK and
 * its RFC 7638 thumbprint are what an admin registers (`POST
 * /v1/workload-identities/:id/credentials`, ADR-0188 S6) before the executor
 * can announce.
 */
import { createPrivateKey, generateKeyPairSync, type KeyObject } from "node:crypto";
import { mkdir, open, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { calculateJwkThumbprint, type JWK } from "jose";
import writeFileAtomic from "write-file-atomic";

export interface ExecutorKey {
  privateKey: KeyObject;
  /** the public half, the only thing that ever leaves this process */
  publicJwk: { kty: "OKP"; crv: "Ed25519"; x: string };
  /** RFC 7638 thumbprint: the `kid` on every proof and signature, and the credential's `jwk_thumbprint` */
  thumbprint: string;
}

async function keyOf(privateKey: KeyObject): Promise<ExecutorKey> {
  const pub = privateKey.export({ format: "jwk" }) as JWK;
  if (pub.kty !== "OKP" || pub.crv !== "Ed25519" || typeof pub.x !== "string") throw new Error("the executor key must be Ed25519");
  const publicJwk = { kty: "OKP" as const, crv: "Ed25519" as const, x: pub.x };
  return { privateKey, publicJwk, thumbprint: await calculateJwkThumbprint(publicJwk, "sha256") };
}

export async function generateExecutorKey(): Promise<ExecutorKey> {
  return keyOf(generateKeyPairSync("ed25519").privateKey);
}

/** load the key at `file` (refusing a file another user can read), or null when absent */
export async function loadExecutorKey(file: string): Promise<ExecutorKey | null> {
  let pem: string;
  try {
    const st = await stat(file);
    // fail closed on a key file readable by group or world: a leaked executor key is an executor
    if (process.platform !== "win32" && (st.mode & 0o077) !== 0) throw new Error(`${file}: the executor key file must be mode 0600`);
    pem = await readFile(file, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw e;
  }
  return keyOf(createPrivateKey({ key: pem, format: "pem" }));
}

/** write the key to `file` (0600, atomic, durable) in a 0700 directory */
export async function saveExecutorKey(file: string, key: ExecutorKey): Promise<void> {
  const dir = path.dirname(file);
  await mkdir(dir, { recursive: true, mode: 0o700 });
  const pem = key.privateKey.export({ format: "pem", type: "pkcs8" }).toString();
  await writeFileAtomic(file, pem, { mode: 0o600, fsync: true });
  // write-file-atomic fsyncs the file; the rename itself is durable only once the directory is
  const fd = await open(dir, "r");
  try {
    await fd.sync();
  } finally {
    await fd.close();
  }
}

/** the stored key, or a new one persisted first (the public half is then shown for an admin to register) */
export async function loadOrCreateExecutorKey(file: string): Promise<{ key: ExecutorKey; created: boolean }> {
  const existing = await loadExecutorKey(file);
  if (existing) return { key: existing, created: false };
  const key = await generateExecutorKey();
  await saveExecutorKey(file, key);
  return { key, created: true };
}
