import { describe,expect,it,vi,beforeEach } from "vitest";
const mocks=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),getBlobWithHeaders:vi.fn()}));
vi.mock("../../../api/client",()=>({api:mocks}));
import { bomB4Api,readB4Bundle,readB4Capabilities,readB4Decision,readB4Verification,sha256 } from "./bomB4Api";
const id="00000000-0000-4000-8000-000000000001",audit="00000000-0000-4000-8000-000000000002",time="2026-10-10T12:00:00.000Z",digest="a".repeat(64);
const caps={access:"admin",exportRoles:"admins_only",auditorGrant:null,canExport:true,exportUnavailableReason:null,canVerify:true,canViewDrift:true,exportRequiresStepUp:false,rateLimitPerMinute:30};
const snapshot={id,version:1,serialNumber:`urn:uuid:${id}`,trigger:"on_demand",bodySha256:digest,keyId:"synthetic",createdAt:time,formats:["cyclonedx-1.7"]},subject={kind:"agent" as const,id};
const common=["bundle_manifest_signature","bundle_manifest_files","bundle_subject","bundle_email_scan","body_version","body_schema","body_signature"];
function ai(){return {trust:"deployment_registry",source:"ai_bom_snapshot",bodyVersion:"regulait.ai-bom.v1",identity:{subject:"ai-bom",snapshotId:id,subjectKind:"agent",subjectId:id,version:1,serialNumber:`urn:uuid:${id}`},outcome:"valid_with_unverifiable",checks:[...common,"rendering_hashes","serial_number","supersedes"].map((check,i)=>({check,status:i<4?"unverifiable":"valid",reason:i<4?"not_a_bundle":null,ref:null as string|null})),sections:[],cannotProve:["facts_true","signing_time_beyond_anchor"],manifest:null,verifiedAt:time,capabilities:caps};}
const expected={source:"ai_bom_snapshot" as const,snapshot,subject};
beforeEach(()=>vi.clearAllMocks());
describe("frozen B4 browser boundary",()=>{
 it("projects full census without raw refs or a supplied key",()=>{const v=ai();v.checks[4]!.ref="private/location";const read=readB4Verification(v,expected);expect(read.inspection.digest).toBe(digest);expect(read.view.trust).toBe("deployment_keys");expect(JSON.stringify(read)).not.toContain("private/location");expect(read.view.sections).toHaveLength(10);});
 it("refuses omitted signature checks and mismatched identity",()=>{const v=ai();v.checks=v.checks.filter(c=>c.check!=="body_signature");expect(()=>readB4Verification(v,expected)).toThrow();const wrong=ai();wrong.identity.snapshotId=audit;expect(()=>readB4Verification(wrong,expected)).toThrow();const version=ai();version.identity.version=2;expect(()=>readB4Verification(version,expected)).toThrow();});
 it("requires actual string enums, reasons, source and reported outcomes",()=>{for(const bad of [["deployment_registry"],{toString:()=>"deployment_registry"},"unknown"]){expect(()=>readB4Verification({...ai(),trust:bad},expected)).toThrow();}expect(()=>readB4Verification({...ai(),source:"decision_bom"},expected)).toThrow();expect(()=>readB4Verification({...ai(),outcome:"valid"},expected)).toThrow();const bad=ai();bad.checks[4]!.reason="not_a_bundle";expect(()=>readB4Verification(bad,expected)).toThrow();});
 it("rejects foreign checks, missing limits and invented stored manifest assurance",()=>{const v=ai();v.checks.push({check:"receipt_signature",status:"valid",reason:null,ref:null});expect(()=>readB4Verification(v,expected)).toThrow();expect(()=>readB4Verification({...ai(),cannotProve:[]},expected)).toThrow();const outer=ai();outer.checks[0]={check:common[0]!,status:"valid",reason:null,ref:null};expect(()=>readB4Verification(outer,expected)).toThrow();});
 it("requires server access/grant and capabilities consistency",()=>{expect(readB4Capabilities(caps).canExport).toBe(true);expect(readB4Capabilities({...caps,canExport:false,exportUnavailableReason:"export_signing_key_absent"}).canExport).toBe(false);for(const bad of [{...caps,access:"auditor_grant"},{...caps,exportRequiresStepUp:true},{...caps,canExport:false},{...caps,canViewDrift:false},{...caps,canVerify:[true]}])expect(()=>readB4Capabilities(bad)).toThrow();});
 it("uses the exact stored verification source with no supplied trust or clock",async()=>{mocks.post.mockResolvedValue(ai());await bomB4Api.inspectSnapshot(id,snapshot,subject);expect(mocks.post).toHaveBeenCalledWith("/v1/boms/verify",{source:"ai_bom_snapshot",snapshotId:id});await expect(bomB4Api.inspectSnapshot(id)).rejects.toThrow();});
 it("base64 encodes bytes, refuses over 8 MiB before any upload",async()=>{await expect(bomB4Api.verify(new Blob([new Uint8Array(8*1024*1024+1)]))).rejects.toThrow();expect(mocks.post).not.toHaveBeenCalled();mocks.post.mockRejectedValue(new Error("synthetic 501"));await expect(bomB4Api.verify(new Blob([new Uint8Array([0,255,1])]))).rejects.toThrow();expect(mocks.post).toHaveBeenCalledWith("/v1/boms/verify",{source:"bundle",bundleBase64:"AP8B"});});
 it("binds archive SHA-256 and body digest before exposing bytes",async()=>{const bytes=new Uint8Array([31,139,8,0]),blob=new Blob([bytes],{type:"application/gzip"});const headers=new Headers({"content-type":"application/gzip","content-disposition":'attachment; filename="regulait-synthetic.tar.gz"',"x-regulait-bundle-schema":"regulait.export-bundle/3","x-regulait-bundle-subject":"ai-bom","x-regulait-bundle-sha256":await sha256(bytes),"x-regulait-bundle-manifest-sha256":digest,"x-regulait-export-signing-key-id":"synthetic","x-regulait-export-signing-key-fingerprint":"sha256:"+digest,"x-regulait-bom-body-sha256":digest});expect(await readB4Bundle(blob,headers,"ai-bom",digest)).toBe(blob);for(const [name,value] of [["content-type","application/zip"],["x-regulait-bundle-subject","decision-bom"],["x-regulait-bundle-sha256",digest],["x-regulait-bom-body-sha256","b".repeat(64)]]){const h=new Headers(headers);h.set(name!,value!);await expect(readB4Bundle(blob,h,"ai-bom",digest)).rejects.toThrow();}});
 it("does not export unrecorded formats or an unfrozen decision",async()=>{await expect(bomB4Api.exportSnapshot(id,"spdx-3.0.1",snapshot,subject)).rejects.toThrow();await expect(bomB4Api.exportDecision(audit)).rejects.toThrow();expect(mocks.getBlobWithHeaders).not.toHaveBeenCalled();});
 it("rejects an unrelated decision response before displaying prose",async()=>{await expect(readB4Decision({auditId:audit,bom:{},document:{SYNTHETIC_SECRET:"never render"}},audit)).rejects.toThrow();});
});
const decisionChecks=["receipt_signature","receipt_payload_hash","receipt_facts_binding","facts_addenda_chain","facts_addenda_signatures","sections_projection","chain_links","decision_content_binding","anchor_record","anchor_imprint","tsa_token","finality","ai_bom_link"];
const sections=["decision","receipt","principal","actors","action","policy","model","approval","outcome","cost","trace","proof"];
function decisionVerify(){return {...ai(),source:"decision_bom",bodyVersion:"regulait.decision-bom.v1",identity:{subject:"decision-bom",auditId:audit,bomId:id,version:2,recordedFinality:"anchored_finite_lock",reportedFinality:"anchored_lapsed",receiptPayloadVersion:"v2"},checks:[...common,...decisionChecks].map((check,i)=>({check,status:i<4||check==="decision_content_binding"?"unverifiable":"valid",reason:i<4?"not_a_bundle":check==="decision_content_binding"?"preimage_not_exported":null,ref:null})),sections:sections.map(section=>({section,status:"valid",completeness:"recorded",notRecordedReason:null})),cannotProve:["nothing_omitted_after_anchor","facts_true","signing_time_beyond_anchor","destination_tamper_resistant","decision_row_content","finite_lock_under_unbounded_retention","commitment_after_retain_until"]};}
describe("Decision verification census and retention",()=>{
 const expected={source:"decision_bom" as const,auditId:audit,version:2};
 it("keeps finite-lock/lapsed distinct and all 20 checks",()=>{const v=readB4Verification(decisionVerify(),expected);expect(v.inspection.finality).toBe("anchored_lapsed");expect(v.view.sections).toHaveLength(20);expect(v.view.cannotProve).toContain("finite_lock_under_unbounded_retention");});
 it("refuses invalid sections with non-invalid outcome and false R39 assurance",()=>{const v=decisionVerify();v.sections[0]!.status="invalid";expect(()=>readB4Verification(v,expected)).toThrow();const projection=decisionVerify();projection.checks.find(c=>c.check==="decision_content_binding")!.status="valid";projection.checks.find(c=>c.check==="decision_content_binding")!.reason=null;expect(()=>readB4Verification(projection,expected)).toThrow();});
 it("refuses a Decision identity for AI source or a different version",()=>{expect(()=>readB4Verification({...decisionVerify(),source:"ai_bom_snapshot"},{source:"ai_bom_snapshot",snapshot,subject})).toThrow();expect(()=>readB4Verification(decisionVerify(),{...expected,version:3})).toThrow();});
 it("refuses missing finite-lock/lapse/v1 limitations",()=>{const v=decisionVerify();v.cannotProve=v.cannotProve.filter(l=>l!=="commitment_after_retain_until");expect(()=>readB4Verification(v,expected)).toThrow();const old=decisionVerify();old.identity.receiptPayloadVersion="v1";expect(()=>readB4Verification(old,expected)).toThrow();});
});
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return "["+value.map(canonical).join(",")+"]";const v=value as Record<string,unknown>;return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}";}
async function decisionRead(){const document={v:"regulait.decision-bom.v1",id,auditId:audit,version:2,supersedes:audit,finality:"anchored_finite_lock",basis:{aiBomSnapshotId:null},completeness:Object.fromEntries(sections.map(s=>[s,{status:"recorded"}]))};const body=canonical(document),bodySha256=await sha256(new TextEncoder().encode(body));const summary={id,version:2,supersedes:audit,finality:"anchored_finite_lock",bodySha256,keyId:"synthetic",createdAt:time};return {auditId:audit,bom:{...summary,body,signature:"a".repeat(86),aiBomSnapshotId:null,reportedFinality:"anchored_lapsed"},document,versions:[{...summary,id:audit,version:1,supersedes:null},summary],renderings:["in-toto"],bundle:{schema:"regulait.export-bundle/3",subject:"decision-bom",href:`/v1/decisions/${audit}/bom/bundle?version=2`},capabilities:caps};}
describe("Decision read metadata and byte binding",()=>{
 it("projects a frozen version then requests that exact version for verification/export",async()=>{const envelope=await decisionRead();mocks.get.mockResolvedValue(envelope);mocks.post.mockResolvedValue(decisionVerify());const inspection=await bomB4Api.decision(audit);expect(inspection.decisionMetadata).toEqual({auditId:audit,bomId:id,version:2,versions:[1,2]});expect(inspection.finality).toBe("anchored_lapsed");expect(mocks.post).toHaveBeenCalledWith("/v1/boms/verify",{source:"decision_bom",auditId:audit,version:2});mocks.getBlobWithHeaders.mockRejectedValue(new Error("synthetic refusal"));await expect(bomB4Api.exportDecision(audit,inspection)).rejects.toThrow();expect(mocks.getBlobWithHeaders).toHaveBeenCalledWith(`/v1/decisions/${audit}/bom/bundle?version=2`);});
 it("refuses changed canonical bytes/digest/document/version summaries",async()=>{for(const mutate of [(v:Awaited<ReturnType<typeof decisionRead>>)=>{v.bom.body+=" ";},(v:Awaited<ReturnType<typeof decisionRead>>)=>{v.bom.bodySha256=digest;},(v:Awaited<ReturnType<typeof decisionRead>>)=>{v.document.auditId=id;},(v:Awaited<ReturnType<typeof decisionRead>>)=>{v.versions.reverse();},(v:Awaited<ReturnType<typeof decisionRead>>)=>{v.versions[1]!.bodySha256=digest;}]){const v=await decisionRead();mutate(v);await expect(readB4Decision(v,audit)).rejects.toThrow();}});
});
it("reports a legitimate unreadable bundle as invalid without invented subject assurance",()=>{const v={...ai(),source:"bundle",identity:null,bodyVersion:null,outcome:"invalid",checks:[{check:"body_schema",status:"invalid",reason:"bundle_unreadable",ref:null}],cannotProve:[]};expect(readB4Verification(v,{source:"bundle"}).view.sections).toEqual([{section:"body_schema",status:"invalid"}]);});
it("refuses contradictory section projection even with an unrelated invalid check",()=>{const v=decisionVerify();v.sections[0]!.status="invalid";v.checks.find(c=>c.check==="body_signature")!.status="invalid";v.checks.find(c=>c.check==="body_signature")!.reason="signature_mismatch";v.outcome="invalid";expect(()=>readB4Verification(v,{source:"decision_bom",auditId:audit,version:2})).toThrow();});
function manifest(decision=false){return {schema:"regulait.export-bundle/3",product:"regulait",installId:"i".repeat(256),installIdSource:"operator",exportedAt:time,exportedAtSource:"database",exportedByUserId:id,subject:decision?{kind:"decision-bom",id:audit,descriptor:{auditId:audit,bomId:id,version:2,finality:"anchored_finite_lock",bodySha256:digest,receiptSeq:5,aiBomSnapshotId:null,formats:[]}}:{kind:"ai-bom",id,descriptor:{snapshotId:id,subjectKind:"agent",subjectId:id,version:1,serialNumber:`urn:uuid:${id}`,trigger:"on_demand",bodySha256:digest,formats:["native"]}},files:[{path:"README.txt",sha256:digest},{path:"content/bom.json",sha256:digest}],audit:decision?{payloadScope:"none",segmentFromSeq:41,segmentToSeq:42,segmentRowCount:2}:null,signingKeyId:"synthetic",signingKeyFingerprint:"sha256:"+digest};}
it("accepts exact manifest positives with 256-character install ID, AI native and Decision audit identity",()=>{const a={...ai(),source:"bundle",outcome:"valid",manifest:manifest(),checks:ai().checks.map(c=>({...c,status:"valid",reason:null}))};expect(readB4Verification(a,{source:"bundle"}).view.trust).toBe("deployment_keys");const d=decisionVerify();const decision={...d,source:"bundle",manifest:manifest(true),checks:d.checks.map(c=>common.slice(0,4).includes(c.check)?{...c,status:"valid",reason:null}:c)};expect(readB4Verification(decision,{source:"bundle"}).identity.auditId).toBe(audit);});
it("refuses malformed manifest IDs, traversal, duplicate paths and overlength values",()=>{for(const mutate of [(m:ReturnType<typeof manifest>)=>{m.installId+="i";},(m:ReturnType<typeof manifest>)=>{m.subject.id=audit;},(m:ReturnType<typeof manifest>)=>{m.files[0]!.path="../README.txt";},(m:ReturnType<typeof manifest>)=>{m.files[1]!.path=m.files[0]!.path;},(m:ReturnType<typeof manifest>)=>{m.files[0]!.path="a".repeat(257);}]){const m=manifest();mutate(m);expect(()=>readB4Verification({...ai(),source:"bundle",outcome:"valid",manifest:m,checks:ai().checks.map(c=>({...c,status:"valid",reason:null}))},{source:"bundle"})).toThrow();}});
